'use client';
import {useState} from 'react';
import {ArrowLeft, Check, CircleHelp, Plus, ShieldCheck, Sparkles, Trash2} from 'lucide-react';
import {uid,faNumber as n} from '@/lib/growth-data';
import {projectBlueprints} from '@/lib/life';
import {Title,type LifeProps} from './shared';

export default function Companion({data,update,go,notify}:LifeProps){
  const [title,setTitle]=useState(''),[outcome,setOutcome]=useState(''),[kind,setKind]=useState<keyof typeof projectBlueprints>('personal'),[minutes,setMinutes]=useState(15),[draft,setDraft]=useState<{title:string;outcome:string;steps:string[];minutes:number;blueprint:keyof typeof projectBlueprints}|null>(null),[busy,setBusy]=useState(false);
  async function accept(){if(!draft||busy||draft.steps.some(s=>!s.trim()))return;setBusy(true);try{const projectId=uid();const snapshot=draft;if(await update(d=>({...d,life:{...d.life,projects:[...d.life.projects,{id:projectId,title:snapshot.title.trim(),outcome:snapshot.outcome.trim(),deadline:'',archived:false,createdAt:new Date().toISOString(),cards:snapshot.steps.map(title=>({id:uid(),title:title.trim(),status:'next' as const,taskId:null}))}]}}))){setDraft(null);setTitle('');setOutcome('');notify('طرح با تأیید تو به کارگاه پروژه اضافه شد.');go('projects')}}finally{setBusy(false)}}
  return <div className="l33"><Title eyebrow="همراه شخصی" title="از «می‌خواهم» به «قدم بعدی»." description="فکرت را روشن کن، یک طرح بساز و قبل از ثبت، آن را به سبک خودت تغییر بده."/>
    <div className="l33-companion-intro"><span className="l33-companion-mark"><Sparkles size={38} strokeWidth={1.2}/></span><div><h2>اینجا با هم، فکر را مرتب می‌کنیم.</h2><p>این همراه، برنامه‌ریز آفلاین با الگوهای مشخص است. به سرویس هوش مصنوعی وصل نیست و داده‌ای به بیرون نمی‌فرستد.</p></div><span className="l33-label"><ShieldCheck size={15}/>روی دستگاه تو</span></div>
    <div className="l33-two"><section className="l33-card"><h2>چه چیزی در ذهن داری؟</h2><form onSubmit={e=>{e.preventDefault();setDraft({title:title.trim(),outcome:outcome.trim(),minutes,blueprint:kind,steps:projectBlueprints[kind].steps.map(step=>`${step} — ${title.trim()}`)})}}><label className="l33-field">اسم هدف یا پروژه<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} placeholder="مثلاً ساخت اولین نمونه‌کار طراحی"/></label><label className="l33-field">از کجا می‌فهمی به نتیجه رسیده‌ای؟<textarea required value={outcome} onChange={e=>setOutcome(e.target.value)} maxLength={2000} rows={3} placeholder="یک خروجی قابل مشاهده بنویس…"/></label><div className="l33-form-row"><label>نوع مسیر<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{Object.entries(projectBlueprints).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><label>اندازه جلسه اول<select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{[5,10,15,25,45].map(v=><option key={v} value={v}>{n(v)} دقیقه</option>)}</select></label></div><button className="l33-button"><Sparkles size={17}/>ساخت طرح قابل ویرایش</button></form></section>
    <section className="l33-card l33-draft" aria-live="polite">{draft?<><div className="l33-card-head"><h2>پیشنهاد برای {draft.title}</h2><span>هنوز ذخیره نشده</span></div><p>{draft.outcome}</p><div className="l33-callout"><CircleHelp size={20}/><p>این قدم‌ها از الگوی «{projectBlueprints[draft.blueprint].label}» آمده‌اند. جلسه اول را {n(draft.minutes)} دقیقه در نظر بگیر؛ زمان‌بندی در تقویم هنوز انجام نشده است.</p></div><ol className="l33-draft-steps">{draft.steps.map((step,i)=><li key={i}><span>{n(i+1)}</span><input aria-label={`عنوان قدم ${i+1}`} value={step} maxLength={300} onChange={e=>setDraft({...draft,steps:draft.steps.map((s,j)=>j===i?e.target.value:s)})}/><button className="l33-icon-button" disabled={draft.steps.length===1} aria-label={`حذف قدم ${i+1}`} onClick={()=>setDraft({...draft,steps:draft.steps.filter((_,j)=>j!==i)})}><Trash2 size={16}/></button></li>)}</ol><button className="l33-link" disabled={draft.steps.length>=20} onClick={()=>setDraft({...draft,steps:[...draft.steps,'']})}><Plus size={15}/>یک قدم دیگر</button><div className="l33-actions"><button className="l33-button" onClick={()=>void accept()} disabled={busy||draft.steps.some(s=>!s.trim())}><Check size={17}/>{busy?'در حال ذخیره…':'تأیید و ساخت پروژه'}</button><button className="l33-link" onClick={()=>setDraft(null)} disabled={busy}>کنار گذاشتن طرح</button></div></>:<div className="l33-companion-empty"><span>✦</span><h2>یک فکر کافی است.</h2><p>طرح پیشنهادی اینجا نمایش داده می‌شود. عنوان‌ها، تعداد قدم‌ها و نتیجه نهایی را خودت تعیین می‌کنی.</p></div>}</section></div>
    <section className="l33-card"><h2>از کدام سمت شروع کنیم؟</h2><div className="l33-three">{[{title:'ذهنم شلوغ است',text:'چند خط بنویس و فکرها را از هم جدا کن.',tab:'journal' as const},{title:'نمی‌دانم چه می‌خواهم',text:'ارزش‌ها و یک تصمیم واقعی را مرور کن.',tab:'reflection' as const},{title:'از برنامه عقب افتاده‌ام',text:'مسیر «شروعی که ادامه دارد» را تجربه کن.',tab:'journeys' as const}].map(item=><button key={item.tab} className="l33-suggestion" onClick={()=>go(item.tab)}><strong>{item.title}</strong><p>{item.text}</p><ArrowLeft size={18}/></button>)}</div></section>
    <p className="l33-muted">کنترل در دست توست: همراه فقط اطلاعات همین فرم را برای پیشنهاد استفاده می‌کند. {data.life.projects.length>0?`${n(data.life.projects.length)} پروژه در کارگاه تو ذخیره شده است.`:''}</p>
  </div>;
}
