'use client';
import {useState} from 'react';
import {ArrowLeft, BookOpen, Check, Clock3, Compass, Pause, Play, Plus, Sprout, Trash2} from 'lucide-react';
import {faNumber as n,uid} from '@/lib/growth-data';
import {journeyTemplates,type JourneyTemplate} from '@/lib/life';
import {Title,Empty,Meter,type LifeProps} from './shared';

export default function Journeys({data,update,go,notify,today}:LifeProps){
  const [selected,setSelected]=useState<string|null>(null),[preview,setPreview]=useState<JourneyTemplate|null>(null),[busy,setBusy]=useState(false),[note,setNote]=useState('');
  const journey=data.life.journeys.find(j=>j.id===selected);
  const nextIndex=journey?.steps.findIndex(s=>!s.doneAt)??-1;
  const lesson=journey?journeyTemplates.find(t=>t.id===journey.template)?.lessons[nextIndex]:undefined;
  async function start(template:JourneyTemplate){if(busy)return;setBusy(true);try{if(data.life.journeys.some(j=>j.template===template.id&&j.steps.some(s=>!s.doneAt))){notify('این مسیر از قبل در فهرست توست.');return}const id=uid();if(await update(d=>({...d,life:{...d.life,journeys:[...d.life.journeys,{id,template:template.id,title:template.title,why:'',startedAt:today,paused:false,steps:template.lessons.map(l=>({id:uid(),title:l.title,note:'',doneAt:null,taskId:null}))}]}}))){setSelected(id);setPreview(null);setNote('');notify('مسیر تو آغاز شد؛ هیچ عجله‌ای برای تمام‌کردن نیست.')}}finally{setBusy(false)}}
  async function finish(){if(!journey||nextIndex<0||busy)return;const step=journey.steps[nextIndex];setBusy(true);try{if(await update(d=>({...d,life:{...d.life,journeys:d.life.journeys.map(j=>j.id===journey.id?{...j,steps:j.steps.map(s=>s.id===step.id?{...s,doneAt:new Date().toISOString(),note}:s)}:j)},tasks:d.tasks.map(t=>t.id===step.taskId?{...t,done:true}:t)}))){setNote('');notify('قدم و یادداشتت ثبت شد.')}}finally{setBusy(false)}}
  async function schedule(){if(!journey||nextIndex<0||busy)return;const step=journey.steps[nextIndex];if(step.taskId&&data.tasks.some(t=>t.id===step.taskId)){go('planner');return}setBusy(true);try{const taskId=uid();if(await update(d=>({...d,tasks:[...d.tasks,{id:taskId,title:`${journey.title}: ${step.title}`,date:today,time:'',priority:'medium',done:false}],life:{...d.life,journeys:d.life.journeys.map(j=>j.id===journey.id?{...j,steps:j.steps.map(s=>s.id===step.id?{...s,taskId}:s)}:j)}})))notify('این قدم به برنامه امروز اضافه شد.')}finally{setBusy(false)}}
  return <div className="l33"><Title eyebrow="مسیرهای رشد" title="از یک قدم، تا یک تغییر." description="تمرین کن، تجربه‌ات را بنویس و با ریتم خودت ادامه بده. این مسیرها تمرین آموزشی‌اند."/>
    {journey?<><button className="l33-link" onClick={()=>{setSelected(null);setNote('')}}>بازگشت به مسیرها<ArrowLeft size={16}/></button><div className="l33-two l33-journey-detail"><section className="l33-card"><span className="l33-eyebrow">مسیر شخصی تو</span><h2>{journey.title}</h2><Meter value={journey.steps.filter(s=>s.doneAt).length/journey.steps.length*100} label="پیشرفت مسیر"/><ol className="l33-steps">{journey.steps.map((s,i)=><li key={s.id} className={s.doneAt?'done':i===nextIndex?'current':''}><span>{s.doneAt?<Check size={16}/>:n(i+1)}</span><div><strong>{s.title}</strong>{s.doneAt&&<small>{new Date(s.doneAt).toLocaleDateString('fa-IR')}</small>}{s.note&&<details><summary>یادداشت این قدم</summary><p>{s.note}</p></details>}</div></li>)}</ol><button className="l33-button secondary" disabled={busy} onClick={()=>void update(d=>({...d,life:{...d.life,journeys:d.life.journeys.map(j=>j.id===journey.id?{...j,paused:!j.paused}:j)}}))}>{journey.paused?<Play size={15}/>:<Pause size={15}/>} {journey.paused?'ادامه مسیر':'مکث در مسیر'}</button></section><section className="l33-card l33-lesson">{journey.paused?<Empty title="مسیر در حالت مکث است" text="هر وقت آماده بودی با همان قدم قبلی ادامه بده."/>:nextIndex<0?<Empty title="این فصل را به پایان رساندی" text="یادداشت‌هایت باقی می‌مانند. برای مسیر بعدی عجله نکن."><button className="l33-button" onClick={()=>go('reflection')}>مرور تجربه من</button></Empty>:<><span className="l33-label"><Clock3 size={15}/>{n(lesson?.minutes||10)} دقیقه · قدم {n(nextIndex+1)}</span><h2>{journey.steps[nextIndex].title}</h2><p className="l33-practice">{lesson?.practice||'این قدم را به اندازه‌ای که امروز برایت ممکن است انجام بده.'}</p><div className="l33-callout"><BookOpen size={19}/><p>{lesson?.question||'از این قدم چه یاد گرفتی؟'}</p></div><label className="l33-field">یادداشت تجربه‌ات (اختیاری)<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={5} placeholder="اینجا فقط برای خودت بنویس…"/></label><div className="l33-actions"><button className="l33-button" disabled={busy} onClick={()=>void finish()}><Check size={17}/>این قدم را انجام دادم</button><button className="l33-button secondary" disabled={busy} onClick={()=>void schedule()}><Plus size={16}/>برنامه امروز</button></div></>}</section></div></>:<>
    {data.life.journeys.length>0&&<section><div className="l33-section-title"><h2>مسیرهای من</h2><span>{n(data.life.journeys.length)} مسیر</span></div><div className="l33-three">{data.life.journeys.map(j=>{const done=j.steps.filter(s=>s.doneAt).length;return <article className="l33-card" key={j.id}><span className="l33-label"><Sprout size={15}/>{j.paused?'در مکث':done===j.steps.length?'تمام‌شده':'در جریان'}</span><h3>{j.title}</h3><p>{n(done)} از {n(j.steps.length)} قدم</p><Meter value={done/j.steps.length*100} label={j.title}/><div className="l33-actions"><button className="l33-link" onClick={()=>{setSelected(j.id);setNote('')}}>باز کردن مسیر<ArrowLeft size={16}/></button><button className="l33-icon-button" aria-label={`حذف مسیر ${j.title}`} onClick={async()=>{if(confirm('مسیر و یادداشت‌های آن حذف شوند؟ کارهای مرتبط در برنامه باقی می‌مانند.'))await update(d=>({...d,life:{...d.life,journeys:d.life.journeys.filter(x=>x.id!==j.id)}}))}}><Trash2 size={16}/></button></div></article>})}</div></section>}
    <section><div className="l33-section-title"><h2>یک فصل تازه انتخاب کن</h2><span>بدون ضرب‌الاجل و زنجیره اجباری</span></div><div className="l33-three">{journeyTemplates.map((t,i)=><article className={`l33-course l33-course-${t.color}`} key={t.id}><div className="l33-course-art" aria-hidden="true"><span className="l33-course-number">0{i+1}</span><Compass size={88} strokeWidth={.8}/><i/><b/></div><div><span className="l33-eyebrow">{t.category} · {n(t.lessons.length)} قدم</span><h2>{t.title}</h2><p>{t.subtitle}</p><button className="l33-link" onClick={()=>setPreview(t)}>دیدن محتوای مسیر<ArrowLeft size={16}/></button></div></article>)}</div></section>
    {preview&&<section className="l33-card l33-preview" aria-label="پیش‌نمایش مسیر"><div className="l33-card-head"><h2>{preview.title}</h2><button className="l33-link" onClick={()=>setPreview(null)}>بستن</button></div><p>می‌توانی چند روز روی یک قدم بمانی. ثبت انجام با انتخاب خودت است.</p><ol>{preview.lessons.map(l=><li key={l.title}><strong>{l.title}</strong><span>{n(l.minutes)} دقیقه</span><p>{l.practice}</p></li>)}</ol><button className="l33-button" disabled={busy} onClick={()=>void start(preview)}>شروع این مسیر<ArrowLeft size={17}/></button></section>}
    </>}
  </div>;
}
