'use client';
import {useState} from 'react';
import {ArrowLeft, BookOpen, Check, Heart, Moon, Plus, Trash2} from 'lucide-react';
import {faNumber as n,lastDays,uid} from '@/lib/growth-data';
import type {Decision} from '@/lib/life';
import {Title,Empty,type LifeProps} from './shared';
export default function Reflection({data,update,go,notify,today}:LifeProps){
  const [busy,setBusy]=useState(false),[decision,setDecision]=useState<Decision|null>(null);
  const entry=data.life.checkins.find(e=>e.date===today);
  const week=lastDays(7,today),observed=data.life.checkins.filter(e=>week.includes(e.date)),average=observed.length?observed.reduce((s,e)=>s+e.energy,0)/observed.length:null;
  async function submitReview(form:HTMLFormElement){if(busy)return;const f=new FormData(form);setBusy(true);try{if(await update(d=>{const old=d.life.checkins.find(e=>e.date===today)||{date:today,energy:3,minutes:15,mode:'grow' as const,mood:3,win:'',lesson:''};return {...d,life:{...d.life,checkins:[...d.life.checkins.filter(e=>e.date!==today),{...old,win:String(f.get('win')||''),lesson:String(f.get('lesson')||'')}].slice(-10000)}}}))notify('مرور امروزت ذخیره شد.')}finally{setBusy(false)}}
  return <div className="l33"><Title eyebrow="آینه شخصی" title="کمی مکث. کمی روشن‌تر." description="تجربه‌ها، ارزش‌ها و تصمیم‌هایت را کنار هم ببین؛ بدون امتیازدهی به خودت."/>
    <div className="l33-two"><section className="l33-card"><h2><Moon size={20}/> پایان روز من</h2><form key={today} onSubmit={e=>{e.preventDefault();void submitReview(e.currentTarget)}}><label className="l33-field">چه چیزی امروز ارزش یادآوری داشت؟<textarea name="win" defaultValue={entry?.win||''} rows={4} maxLength={3000} placeholder="یک اتفاق کوچک هم کافی است…"/></label><label className="l33-field">چه آموختم یا فردا چه چیزی را تغییر می‌دهم؟<textarea name="lesson" defaultValue={entry?.lesson||''} rows={3} maxLength={3000}/></label><button className="l33-button" disabled={busy}><Check size={16}/>ذخیره مرور روز</button></form></section><section className="l33-card"><span className="l33-eyebrow">براساس ثبت‌های تو</span><h2>تصویر هفت روز اخیر</h2><div className="l33-metrics"><div><strong>{n(observed.length)}</strong><small>روز ثبت حال</small></div><div><strong>{average===null?'—':n(average)}</strong><small>میانگین انرژی از ۵</small></div></div><p>این اعداد توصیف ثبت‌های تو هستند؛ اندازه‌گیری سلامت، تشخیص یا توضیح علت تغییر احساس نیستند.</p><div className="l33-energy-list">{week.map(day=>{const e=observed.find(x=>x.date===day);return <div key={day}><span>{new Date(`${day}T12:00:00`).toLocaleDateString('fa-IR',{weekday:'short'})}</span><div>{[1,2,3,4,5].map(i=><i key={i} className={e&&i<=e.energy?'filled':''}/>)}</div><small>{e?n(e.energy):'ثبت نشده'}</small></div>})}</div><button className="l33-link" onClick={()=>go('insights')}>گزارش فعالیت‌ها<ArrowLeft size={16}/></button></section></div>
    <section className="l33-card"><div className="l33-card-head"><h2><Heart size={18}/> قطب‌نمای ارزش‌های من</h2><span>حداکثر هشت ارزش</span></div><p>چیزهایی که می‌خواهی در رفتار و انتخاب‌هایت دیده شوند؛ مثل یادگیری، صداقت، خانواده یا استقلال.</p><form onSubmit={async e=>{e.preventDefault();const values=[...new Set(String(new FormData(e.currentTarget).get('values')||'').split(/[,،\n]/).map(v=>v.trim()).filter(Boolean))];if(values.length>8||values.some(v=>v.length>60)){notify('حداکثر هشت ارزش کوتاه بنویس.');return}if(await update(d=>({...d,life:{...d.life,values}})))notify('ارزش‌هایت ثبت شدند.')}}><label className="l33-field">با ویرگول جدا کن<input name="values" defaultValue={data.life.values.join('، ')} maxLength={480}/></label><button className="l33-button secondary">ذخیره ارزش‌ها</button></form></section>
    <section className="l33-card"><div className="l33-card-head"><h2>دفتر تصمیم‌ها</h2><button className="l33-button secondary" onClick={()=>setDecision({id:uid(),title:'',values:data.life.values.join('، '),options:'',choice:'',reviewOn:'',result:'',createdAt:new Date().toISOString()})}><Plus size={16}/>تصمیم جدید</button></div>{decision&&<form className="l33-decision-form" key={decision.id} onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget),value={...decision,title:String(f.get('title')||'').trim(),values:String(f.get('values')||''),options:String(f.get('options')||''),choice:String(f.get('choice')||''),reviewOn:String(f.get('reviewOn')||''),result:String(f.get('result')||'')};setBusy(true);try{if(await update(d=>({...d,life:{...d.life,decisions:[value,...d.life.decisions.filter(x=>x.id!==value.id)]}}))){setDecision(null);notify('تصمیم ذخیره شد.')}}finally{setBusy(false)}}}><label className="l33-field">درباره چه چیزی تصمیم می‌گیرم؟<input autoFocus name="title" required maxLength={300} defaultValue={decision.title}/></label><label className="l33-field">ارزش‌ها و محدودیت‌های مهم<input name="values" maxLength={1200} defaultValue={decision.values}/></label><label className="l33-field">گزینه‌ها، شواهد و هزینه هر انتخاب<textarea name="options" rows={4} maxLength={4000} defaultValue={decision.options}/></label><label className="l33-field">انتخاب فعلی و دلیل آن<textarea name="choice" rows={2} maxLength={2000} defaultValue={decision.choice}/></label><label className="l33-field">تاریخ مرور (درون اپ؛ بدون اعلان خودکار)<input type="date" name="reviewOn" defaultValue={decision.reviewOn}/></label><label className="l33-field">پس از اجرا چه اتفاقی افتاد؟<textarea name="result" rows={2} maxLength={2000} defaultValue={decision.result}/></label><div className="l33-actions"><button className="l33-button" disabled={busy}>ذخیره تصمیم</button><button type="button" className="l33-link" onClick={()=>setDecision(null)}>انصراف</button></div></form>}{data.life.decisions.map(d=><article className="l33-decision" key={d.id}><div><span className="l33-label">{d.reviewOn&&d.reviewOn<=today&&!d.result?'زمان مرور رسیده':d.result?'مرور شده':'در جریان'}</span><h3>{d.title}</h3><p>{d.choice||'هنوز انتخابی ثبت نشده.'}</p></div><div className="l33-actions"><button className="l33-link" onClick={()=>setDecision(d)}>باز کردن و مرور</button><button className="l33-icon-button" aria-label={`حذف تصمیم ${d.title}`} onClick={()=>{if(confirm('این تصمیم و یادداشت آن حذف شوند؟'))void update(s=>({...s,life:{...s.life,decisions:s.life.decisions.filter(x=>x.id!==d.id)}}))}}><Trash2 size={16}/></button></div></article>)}{!data.life.decisions.length&&!decision&&<Empty title="فکر امروز، یادگیری فردا" text="دلیل انتخابت را امروز بنویس تا بعداً با نتیجه واقعی مقایسه کنی."/>}</section>
    <section className="l33-card"><h2><BookOpen size={19}/> مرورهای گذشته</h2>{data.life.checkins.filter(e=>e.win||e.lesson).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).map(e=><details className="l33-review" key={e.date}><summary>{new Date(`${e.date}T12:00:00`).toLocaleDateString('fa-IR',{day:'numeric',month:'long',year:'numeric'})}</summary><p>{e.win}</p><p>{e.lesson}</p></details>)}{!data.life.checkins.some(e=>e.win||e.lesson)&&<p>با نوشتن اولین مرور، این فضا به دفتر تجربه‌هایت تبدیل می‌شود.</p>}</section>
  </div>;
}
