'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft, Cloud, Download, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, Upload} from 'lucide-react';
import {faNumber as n,makeBackup,type GrowthData} from '@/lib/growth-data';
import {decryptVault,downloadJson,encryptVault} from '@/lib/vault-client';
import {vaultEnvelopeSchema,type VaultEnvelope} from '@/lib/vault-format';
import type {Member} from '@/lib/community/types';
import {Title,type LifeProps} from './shared';
type Remote={memberId:string;revision:number;envelope:VaultEnvelope|null;updatedAt:string|null};
type Account={user:Member;sessions:{current:boolean;expiresAt:number}[]};
async function request<T>(path:string,body?:object):Promise<T>{const response=await fetch(path,{method:body?'POST':'GET',cache:'no-store',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(25000)});const value=await response.json();if(!response.ok)throw new Error(value.error||'ارتباط با سرور برقرار نشد.');return value as T}

export default function Trust({data,update,go,notify,today}:LifeProps){
  const [account,setAccount]=useState<Account|null>(null),[remote,setRemote]=useState<Remote|null>(null),[loading,setLoading]=useState(true),[status,setStatus]=useState(''),[passphrase,setPassphrase]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{data:GrowthData;baseline:string}|null>(null),[downloaded,setDownloaded]=useState(false);
  const generation=useRef(0),file=useRef<HTMLInputElement>(null);
  const [exportCursor,setExportCursor]=useState<number|null>(0),[exportPage,setExportPage]=useState(1);
  async function refresh(){const key=++generation.current;setLoading(true);setStatus('');setPreview(null);setRemote(null);setAccount(null);setPassphrase('');setExportCursor(0);setExportPage(1);try{const a=await request<Account>('/api/account');if(key!==generation.current)return;setAccount(a);const r=await request<Remote>('/api/vault');if(key!==generation.current)return;if(r.memberId!==a.user.id)throw new Error('حساب فعال تغییر کرده است. دوباره وضعیت را دریافت کن.');if(r.envelope)vaultEnvelopeSchema.parse(r.envelope);setRemote(r)}catch(error){if(key===generation.current)setStatus(error instanceof Error?error.message:'دریافت وضعیت ناموفق بود.')}finally{if(key===generation.current)setLoading(false)}}
  useEffect(()=>{void refresh();const reset=()=>{void refresh()};window.addEventListener('roshana:session',reset);return()=>{generation.current++;window.removeEventListener('roshana:session',reset)}},[]);
  async function perform(work:()=>Promise<void>){if(busy)return;setBusy(true);setStatus('');try{await work()}catch(error){setStatus(error instanceof Error?error.message:'عملیات انجام نشد.')}finally{setBusy(false)}}
  function backup(){downloadJson(JSON.parse(makeBackup(data)),`roshana-local-${today}.json`);setDownloaded(true)}
  function prepare(value:GrowthData){setPreview({data:value,baseline:makeBackup(data)});setDownloaded(false);setPassphrase('')}
  function generateRandomPassphrase(){
    const words = ['roshana', 'sky', 'growth', 'mind', 'peace', 'focus', 'zen', 'lotus', 'light', 'star'];
    const part1 = words[Math.floor(Math.random() * words.length)];
    const part2 = words[Math.floor(Math.random() * words.length)];
    const num = Math.floor(1000 + Math.random() * 9000);
    const pass = `${part1}-${part2}-${num}-secure`;
    setPassphrase(pass);
    if(navigator.clipboard){
      navigator.clipboard.writeText(pass);
      setStatus('گذرواژه امن تصادفی تولید و در حافظه کپی شد: ' + pass);
    }
  }
  return <div className="l33"><Title eyebrow="مرکز اعتماد" title="اطلاعات تو. انتخاب تو." description="ببین چه چیزی کجا نگه‌داری می‌شود؛ پشتیبان بگیر و انتقال را خودت کنترل کن."/>
    <div className="l33-three">{[{icon:ShieldCheck,title:'فضای شخصی',text:'برنامه، دفتر، مسیر و پروژه در حافظه همین مرورگر ذخیره می‌شوند. این حافظه به‌خودی‌خود رمزگذاری اختصاصی ندارد.'},{icon:Cloud,title:'حساب و گفتگو',text:'پروفایل، پیام‌ها و بازی آنلاین روی سرورند. گفتگو رمزگذاری سرتاسری ندارد؛ اطلاعات حساس را در چت عمومی ننویس.'},{icon:KeyRound,title:'خزانه اختیاری',text:'نسخه شخصی با گذرواژه جدا روی همین دستگاه رمز می‌شود. فقط پس از انتخاب ارسال، نسخه رمز‌شده به سرور می‌رود.'}].map(item=><section className="l33-card" key={item.title}><span className="l33-token"><item.icon size={23}/></span><h2>{item.title}</h2><p>{item.text}</p></section>)}</div>
    <section className="l33-card"><div className="l33-card-head"><h2><LockKeyhole size={19}/> خزانه و انتقال بین دستگاه‌ها</h2><span>دستی · بدون ادغام خودکار</span></div><p>برای بازیابی به همان گذرواژه نیاز داری؛ مدیر نمی‌تواند آن را بازیابی کند. یک عبارت بلند و یکتا انتخاب کن و در جای امن نگه دار. نسخه آنلاین حداکثر یک مگابایت داده شخصی می‌پذیرد.</p><div style={{display:'flex',gap:'8px',alignItems:'flex-end'}}><label className="l33-field" style={{flex:1,margin:0}}>گذرواژه خزانه<input type="password" value={passphrase} onChange={e=>setPassphrase(e.target.value)} minLength={12} maxLength={256} autoComplete="off" placeholder="حداقل ۱۲ نویسه؛ متفاوت از رمز حساب"/></label><button className="l33-button secondary" type="button" onClick={generateRandomPassphrase} title="تولید عبارت عبور امن تصادفی">تولید رمز امن</button></div><div className="l33-actions" style={{marginTop:'16px'}}><button className="l33-button secondary" disabled={busy||passphrase.length<12} onClick={()=>void perform(async()=>{const envelope=await encryptVault(data,passphrase);downloadJson(envelope,`roshana-encrypted-${today}.json`);setPassphrase('');setStatus('فایل رمزگذاری‌شده برای دانلود آماده شد.')})}><Download size={16}/>دانلود فایل رمزگذاری‌شده</button><button className="l33-button secondary" disabled={busy||passphrase.length<12} onClick={()=>file.current?.click()}><Upload size={16}/>باز کردن فایل رمزگذاری‌شده</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={e=>{const selected=e.target.files?.[0];e.target.value='';if(!selected)return;void perform(async()=>{if(selected.size>1_400_000)throw new Error('حجم فایل از سقف خزانه بیشتر است.');prepare(await decryptVault(JSON.parse(await selected.text()),passphrase))})}}/></div>
    <div className="l33-divider"/>
    {loading?<p role="status">در حال دریافت وضعیت حساب…</p>:!account?<div className="l33-callout"><Cloud size={20}/><p>برای خزانه سرور وارد حساب گفتگو شو. فایل رمزگذاری‌شده بدون حساب هم کار می‌کند.</p><button className="l33-link" onClick={()=>go('community')}>ورود به حساب<ArrowLeft size={15}/></button></div>:<><div className="l33-card-head"><p>حساب: <strong>{account.user.displayName}</strong></p><button className="l33-link" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15}/>دریافت وضعیت تازه</button></div><p>{!remote?'وضعیت خزانه سرور هنوز در دسترس نیست.':remote.envelope?`نسخه ${n(remote.revision)} · آخرین تغییر ${new Date(remote.updatedAt!).toLocaleString('fa-IR')}`:'نسخه‌ای در خزانه سرور ذخیره نشده است.'}</p><div className="l33-actions"><button className="l33-button" disabled={busy||!remote||passphrase.length<12} onClick={()=>{if(!remote)return;if(!confirm('نسخه شخصی این دستگاه رمزگذاری و در حساب فعلی ذخیره شود؟ اگر خزانه‌ای هست، جایگزین خواهد شد.'))return;void perform(async()=>{const key=generation.current;const current=await request<Remote>('/api/vault');if(current.memberId!==remote.memberId||current.revision!==remote.revision)throw new Error('نسخه یا حساب سرور تغییر کرده؛ وضعیت تازه را بگیر.');if(current.envelope)await decryptVault(current.envelope,passphrase);const envelope=await encryptVault(data,passphrase);if(key!==generation.current)return;const saved=await request<Remote>('/api/vault',{memberId:remote.memberId,revision:remote.revision,envelope});if(key!==generation.current)return;setRemote(saved);setPassphrase('');setStatus('نسخه رمزگذاری‌شده در سرور ذخیره شد.')})}}><Cloud size={16}/>ذخیره نسخه این دستگاه در سرور</button><button className="l33-button secondary" disabled={busy||!remote?.envelope||passphrase.length<12} onClick={()=>void perform(async()=>{if(!remote?.envelope)return;const key=generation.current;const decoded=await decryptVault(remote.envelope,passphrase);if(key===generation.current)prepare(decoded)})}>بازکردن نسخه سرور</button><button className="l33-link danger" disabled={busy||!remote?.envelope} onClick={()=>{if(!remote||!confirm('نسخه رمزگذاری‌شده خزانه از سرور حذف شود؟ اطلاعات دستگاه باقی می‌ماند؛ نسخه‌های پشتیبان سرور ممکن است تا پایان دوره نگه‌داری باقی بمانند.'))return;void perform(async()=>{const key=generation.current,saved=await request<Remote>('/api/vault',{memberId:remote.memberId,revision:remote.revision,envelope:null});if(key===generation.current){setRemote(saved);setPreview(null);setStatus('نسخه فعال خزانه سرور حذف شد.')}})}}>حذف نسخه سرور</button></div></>}
    {status&&<p className="l33-status" role="status">{status}</p>}
    {preview&&<section className="l33-restore"><h3>پیش‌نمایش نسخه بازشده</h3><p>{n(preview.data.tasks.length)} کار، {n(preview.data.journal.length)} یادداشت، {n(preview.data.life.projects.length)} پروژه و {n(preview.data.life.journeys.length)} مسیر. اعمال این نسخه، اطلاعات شخصی فعلی را جایگزین می‌کند.</p><div className="l33-actions"><button className="l33-button secondary" onClick={backup}><Download size={16}/>ابتدا پشتیبان اطلاعات فعلی</button><button className="l33-button" disabled={busy||!downloaded} onClick={()=>{if(!confirm('فایل پشتیبان فعلی را ذخیره کرده‌ای و می‌خواهی داده این دستگاه با نسخه بازشده جایگزین شود؟'))return;void perform(async()=>{if(await update(current=>{if(makeBackup(current)!==preview.baseline)throw new Error('اطلاعات محلی بعد از پیش‌نمایش تغییر کرده است.');return preview.data})){setPreview(null);setStatus('نسخه بازشده روی این دستگاه اعمال شد.')}else setStatus('جایگزینی انجام نشد. اگر اطلاعات تغییر کرده، نسخه را دوباره باز کن.')})}}>تأیید جایگزینی اطلاعات</button><button className="l33-link" onClick={()=>setPreview(null)}>انصراف</button></div></section>}
    </section>
    <section className="l33-card"><h2>دستگاه‌ها و خروجی حساب</h2>{account?<><p>{n(account.sessions.length)} نشست فعال؛ اطلاعات مرورگر یا مکان نشست‌ها ذخیره نمی‌شود.</p><ul className="l33-session-list">{account.sessions.map((s,i)=><li key={i}><span>{s.current?'نشست فعلی':'نشست دیگر'}</span><small>انقضا: {new Date(s.expiresAt).toLocaleDateString('fa-IR')}</small></li>)}</ul><div className="l33-actions"><button className="l33-button secondary" disabled={busy||account.sessions.length<2} onClick={()=>{if(!confirm('ورودهای دیگر این حساب بسته شوند؟ نشست فعلی باز می‌ماند.'))return;void perform(async()=>{const key=generation.current,result=await request<{sessions:Account['sessions']}>('/api/account',{action:'revoke-others'});if(key===generation.current){setAccount({...account,sessions:result.sessions});setStatus('نشست‌های دیگر بسته شدند.')}})}}>خروج از نشست‌های دیگر</button><button className="l33-button secondary" disabled={busy} onClick={()=>downloadJson({profile:account.user,exportedAt:new Date().toISOString()},`roshana-profile-${today}.json`)}>دانلود پروفایل</button><button className="l33-button secondary" disabled={busy||exportCursor===null} onClick={()=>void perform(async()=>{const key=generation.current;const result=await request<{memberId:string;messages:unknown[];next:number|null}>(`/api/account?export=messages&cursor=${exportCursor||0}`);if(result.memberId!==account.user.id||key!==generation.current)throw new Error('حساب تغییر کرد؛ دریافت متوقف شد.');downloadJson(result,`roshana-my-messages-${today}-${exportPage}.json`);setExportCursor(result.next);setExportPage(p=>p+1);setStatus(result.next===null?'همه صفحه‌های متن پیام‌ها دریافت شد. فایل‌های پیوست در این خروجی نیستند.':'این صفحه شامل حداکثر ۲۰۰ پیام است. برای ادامه دکمه صفحه بعد را بزن.')})}>{exportCursor===null?'تمام پیام‌ها دریافت شدند':`دانلود متن پیام‌ها · صفحه ${n(exportPage)}`}</button></div><p>برای تغییر رمز یا حذف حساب و داده‌های فعال آن، از تنظیمات حساب در بخش گفتگو استفاده کن.</p><button className="l33-link" onClick={()=>go('community')}>تنظیمات حساب<ArrowLeft size={15}/></button></>:<p>مدیریت نشست و خروجی حساب پس از ورود در دسترس است.</p>}</section>
    <section className="l33-card"><h2>چیدمان خانه تو</h2><div className="l33-actions">{[{id:'balanced' as const,label:'متعادل'},{id:'quiet' as const,label:'آرام؛ بدون کارت‌های کشف'},{id:'compact' as const,label:'فشرده'}].map(item=><button className="l33-chip" key={item.id} aria-pressed={data.life.layout===item.id} onClick={()=>void update(d=>({...d,life:{...d.life,layout:item.id}}))}>{item.label}</button>)}</div><button className="l33-link" onClick={()=>go('settings')}>رنگ‌ها، ظاهر و تنظیمات پشتیبان<ArrowLeft size={15}/></button></section>
    <section className="l33-card"><h2>قواعد روشن روشنا</h2><details className="l33-review"><summary>حریم خصوصی و نگه‌داری</summary><p>داده شخصی تا حذف از مرورگر یا جایگزینی پشتیبان روی دستگاه می‌ماند. حساب، پیام‌ها و بازی آنلاین در سرور نگه‌داری می‌شوند. حذف حساب، نام را ناشناس و متن پیام‌های خودت را از نسخه فعال پاک می‌کند؛ سوابق محدود گزارش و بازی برای یکپارچگی باقی می‌مانند. پشتیبان‌های سرور طبق تنظیم پیش‌فرض تا ۳۰ نوبت نگه‌داری می‌شوند. آمار استفاده فقط با انتخاب کاربر فعال است و شمارش تجمیعی بخش‌هاست.</p></details><details className="l33-review"><summary>قواعد جامعه</summary><p>به حریم خصوصی دیگران احترام بگذار. آزار، تهدید، انتشار اطلاعات خصوصی و فریب ممنوع است. گزارش و بلاک در گفتگو در دسترس‌اند. مدیر می‌تواند محتوای گزارش‌شده را بررسی و حساب متخلف را تعلیق کند.</p></details><details className="l33-review"><summary>محدوده خدمات</summary><p>تمرین‌ها برای آموزش و تأمل شخصی‌اند و جای تشخیص یا درمان تخصصی را نمی‌گیرند. اطلاعات بازار همراه منبع است و توصیه سرمایه‌گذاری محسوب نمی‌شود. خرید اشتراک، خدمات متخصص، تماس تصویری و پرداخت در این نسخه فعال نیستند.</p></details></section>
  </div>;
}
