'use client';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import {Ban,EyeOff,Flag,MessageCircle,RefreshCw,RotateCcw,ShieldCheck,Users} from 'lucide-react';

type Report={id:string;reason:string;created_at:string;status:string;reporter_name:string;message_body:string|null;target_id:string;target_name:string|null;target_suspended:number|null;message_id:string|null};
type Overview={counts:{members:number;messages:number;reports:number};reports:Report[];suspended:{id:string;username:string;display_name:string}[]};
async function request(body?:object){const response=await fetch('/api/community/admin',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'درخواست مدیریت جامعه انجام نشد.');return data;}

export default function CommunityAdmin(){
  const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setBusy(true);try{setData(await request());setError('')}catch(reason){setError(reason instanceof Error?reason.message:'دریافت گزارش‌ها ممکن نشد.')}finally{setBusy(false)}},[]);
  useEffect(()=>{void load()},[load]);
  async function act(action:'resolve'|'hide-message'|'suspend'|'restore',report?:Report,memberId?:string){
    const destructive=action==='hide-message'||action==='suspend';
    if(destructive&&!confirm(action==='suspend'?'این حساب تعلیق و نشست‌های آن بسته شود؟':'این پیام و فایل پیوست آن پنهان شود؟'))return;
    setBusy(true);try{await request({action,...(report?{reportId:report.id}:{}),...(memberId?{memberId}:{})});await load()}catch(reason){setError(reason instanceof Error?reason.message:'عملیات انجام نشد.');setBusy(false)}
  }
  return <section className="admin-community"><div className="admin-card-heading"><div><h2>سلامت جامعه</h2><p className="admin-muted">گزارش‌ها را با زمینه کافی بررسی کنید. گزارش به‌تنهایی اثبات تخلف نیست.</p></div><button className="admin-text-button" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/>تازه‌سازی</button></div>{error&&<div className="admin-status admin-status-error" role="alert">{error}</div>}{!data?<div className="admin-card">{busy?'در حال دریافت اطلاعات…':'اطلاعات در دسترس نیست.'}</div>:<><div className="admin-stats"><Stat icon={<Users size={21}/>} label="حساب فعال" value={data.counts.members}/><Stat icon={<MessageCircle size={21}/>} label="پیام نمایان" value={data.counts.messages}/><Stat icon={<Flag size={21}/>} label="گزارش باز" value={data.counts.reports}/></div><div className="admin-moderation-grid"><section className="admin-card"><h2>گزارش‌های اخیر</h2>{data.reports.length?<div className="admin-report-list">{data.reports.map(report=><article key={report.id} className={report.status==='open'?'is-open':''}><header><strong>{report.target_name||'مورد حذف‌شده'}</strong><span>{report.status==='open'?'باز':'بررسی‌شده'}</span></header><p>{report.reason}</p>{report.message_body&&<blockquote>{report.message_body.slice(0,500)}</blockquote>}<small>گزارش‌دهنده: {report.reporter_name} · {new Date(report.created_at).toLocaleString('fa-IR')}</small>{report.status==='open'&&<div><button disabled={busy} onClick={()=>void act('resolve',report)}><ShieldCheck size={15}/>بستن گزارش</button>{report.message_id&&<button disabled={busy} onClick={()=>void act('hide-message',report)}><EyeOff size={15}/>پنهان‌کردن پیام</button>}<button className="danger" disabled={busy||Boolean(report.target_suspended)} onClick={()=>void act('suspend',report)}><Ban size={15}/>تعلیق حساب</button></div>}</article>)}</div>:<p className="admin-muted">گزارشی ثبت نشده است.</p>}</section><section className="admin-card"><h2>حساب‌های تعلیق‌شده</h2>{data.suspended.length?<div className="admin-suspended-list">{data.suspended.map(member=><div key={member.id}><span><strong>{member.display_name}</strong><small dir="ltr">@{member.username}</small></span><button disabled={busy} onClick={()=>void act('restore',undefined,member.id)}><RotateCcw size={15}/>بازگردانی</button></div>)}</div>:<p className="admin-muted">حساب تعلیق‌شده‌ای وجود ندارد.</p>}<div className="admin-info"><ShieldCheck size={19}/><span>حذف پیام و تعلیق حساب در دفتر ممیزی ثبت می‌شود. متن ژورنال، هدف و برنامه شخصی کاربران به این پنل ارسال نمی‌شود.</span></div></section></div></>}</section>;
}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <article className="admin-card admin-stat"><div className="admin-stat-top"><span>{label}</span><span className="admin-stat-icon">{icon}</span></div><strong>{value.toLocaleString('fa-IR')}</strong></article>}
