'use client';

import {useCallback, useEffect, useRef, useState} from 'react';
import dynamic from 'next/dynamic';
import {Gamepad2, MessageCircle, Newspaper, Tv, Bot, Radio, Trophy} from 'lucide-react';
import {destinations,readPreferences,type Destination} from '@/lib/product';
import {DiscoveryDeck,FavoritesRail,GlobalSearch,NotificationCenter,Personalization,Onboarding,UsageSignal,ModuleSkeleton,ModuleBoundary} from '@/components/super-shell';
import {Activity, ArrowLeft, ArrowRight, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Download, Flame, Flower2, Focus, Heart, LayoutDashboard, Leaf, Menu, MoreHorizontal, Pencil, Plus, Search, Settings, ShieldCheck, Sparkles, Sprout, Target, Trash2, TrendingUp, Upload, WifiOff, X} from 'lucide-react';
import {useGrowthData} from '@/hooks/use-growth-data';
import {dayKey, emptyData, faNumber as n, habitStreak, lastDays, shiftDay, uid, type Task, type Goal, type Habit, type JournalEntry, type GrowthData} from '@/lib/growth-data';
import {appConfigSchema, defaultConfig, type AppConfig, type Resource} from '@/lib/app-config';
import {PwaManager} from '@/components/pwa-manager';
import Gadgets from '@/components/gadgets';
import ReminderSettings from '@/components/reminder-settings';
import {ThemePicker} from '@/components/theme';
import {DashboardShortcuts} from '@/components/dashboard-shortcuts';
import {getTelegramUser, setupTelegramBackButton, triggerHaptic} from '@/lib/telegram/webapp';

type Tab = Destination;
const CommunityHub=dynamic(()=>import('@/components/community-hub'),{loading:ModuleSkeleton});
const MarketHub=dynamic(()=>import('@/components/market-hub'),{loading:ModuleSkeleton});
const GameCenter=dynamic(()=>import('@/components/game-center'),{loading:ModuleSkeleton});
const Today=dynamic(()=>import('@/components/life/today'),{loading:ModuleSkeleton});
const Journeys=dynamic(()=>import('@/components/life/journeys'),{loading:ModuleSkeleton});
const Projects=dynamic(()=>import('@/components/life/projects'),{loading:ModuleSkeleton});
const Companion=dynamic(()=>import('@/components/life/companion'),{loading:ModuleSkeleton});
const Reflection=dynamic(()=>import('@/components/life/reflection'),{loading:ModuleSkeleton});
const Trust=dynamic(()=>import('@/components/life/trust'),{loading:ModuleSkeleton});
const LanguageHub=dynamic(()=>import('@/components/language-hub'),{loading:ModuleSkeleton});
const MeditationHub=dynamic(()=>import('@/components/meditation-hub'),{loading:ModuleSkeleton});
const WorkoutHub=dynamic(()=>import('@/components/workout-hub'),{loading:ModuleSkeleton});
const SelfDiscoveryHub=dynamic(()=>import('@/components/self-discovery-hub'),{loading:ModuleSkeleton});
const LiveTV=dynamic(()=>import('@/components/live-tv'),{loading:ModuleSkeleton});
const RadioHub=dynamic(()=>import('@/components/radio-hub'),{loading:ModuleSkeleton});
const AiMentor=dynamic(()=>import('@/components/ai-mentor'),{loading:ModuleSkeleton});
const GamificationHub=dynamic(()=>import('@/components/gamification-hub'),{loading:ModuleSkeleton});
const MonthlyAnalytics=dynamic(()=>import('@/components/monthly-analytics'),{loading:ModuleSkeleton});
type Edit = {type:'task';value:Task}|{type:'goal';value:Goal}|{type:'habit';value:Habit}|{type:'journal';value:JournalEntry}|{type:'resource';value:Resource}|null;
const navigation: {id:Tab;label:string;icon:typeof Leaf}[] = [
  {id:'mentor',label:'مربی زندگی AI',icon:Bot as any},{id:'challenges',label:'افتخارات و چالش‌ها',icon:Trophy as any},{id:'radio',label:'رادیو آرامش',icon:Radio as any},
  {id:'companion',label:'همراه',icon:Sparkles},{id:'journeys',label:'مسیرهای رشد',icon:Sprout},{id:'projects',label:'کارگاه پروژه',icon:Target},{id:'reflection',label:'آینه شخصی',icon:Heart},{id:'trust',label:'مرکز اعتماد',icon:ShieldCheck},{id:'overview',label:'نمای کلاسیک',icon:LayoutDashboard},
  {id:'home',label:'خانه',icon:LayoutDashboard},{id:'community',label:'گفتگو',icon:MessageCircle},{id:'markets',label:'اخبار و بازار',icon:Newspaper},{id:'tv',label:'تلویزیون زنده',icon:Tv as any},{id:'games',label:'بازی',icon:Gamepad2},{id:'planner',label:'برنامه‌ریزی',icon:CalendarDays},{id:'goals',label:'هدف‌های من',icon:Target},
  {id:'habits',label:'عادت‌های کوچک',icon:Flame},{id:'journal',label:'دفتر خودشناسی',icon:BookOpen},{id:'wheel',label:'چرخه زندگی',icon:Flower2},
  {id:'focus',label:'زمان تمرکز',icon:Focus},{id:'insights',label:'گزارش رشد',icon:TrendingUp},{id:'library',label:'کتابخانه رشد',icon:Sprout},
  {id:'self-discovery',label:'خودشناسی و خداشناسی',icon:Sparkles},{id:'meditation',label:'مدیتیشن',icon:Flower2},{id:'workout',label:'ورزش روزانه',icon:Activity},{id:'gadgets',label:'گجت',icon:Sparkles},{id:'language',label:'زبان‌آموز',icon:BookOpen},
];
const domains = ['سلامت جسم','آرامش ذهن','رابطه‌ها','خانواده','کار و یادگیری','وضعیت مالی','تفریح','معنا و ارزش‌ها'];
const prompts = ['امروز چه چیزی به من انرژی داد و چه چیزی از من انرژی گرفت؟','اگر قرار باشد امروز فقط یک قدم بردارم، آن قدم چیست؟','کدام نیازم را نادیده گرفته‌ام و چطور می‌توانم به آن توجه کنم؟','چه چیزی در کنترل من است و چه چیزی را می‌توانم رها کنم؟','کدام رفتار کوچک امروز با ارزش‌های من هماهنگ بود؟','در یک گفت‌وگوی اخیر، واقعاً چه احساسی داشتم؟','این هفته چه چیزی درباره خودم یاد گرفتم؟'];
const moods = [{emoji:'😔',label:'سنگین'},{emoji:'😕',label:'کمی گرفته'},{emoji:'😐',label:'معمولی'},{emoji:'🙂',label:'خوب'},{emoji:'😄',label:'عالی'}];
const priorityLabels={high:'مهم',medium:'معمولی',low:'آرام و پیوسته'};
const faDate=(key:string, options:Intl.DateTimeFormatOptions={day:'numeric',month:'long'})=>new Date(`${key}T12:00:00`).toLocaleDateString('fa-IR',options);
const percent=(a:number,b:number)=>b?Math.min(100,Math.round(a/b*100)):0;

function GrowthArt(){return <svg viewBox="0 0 350 240" aria-hidden="true" className="g-growth-art"><defs><linearGradient id="arch" x2="1" y2="1"><stop stopColor="#779383"/><stop offset="1" stopColor="#295e4f"/></linearGradient></defs><circle cx="167" cy="78" r="53" fill="#e6dc9d"/><circle cx="280" cy="37" r="4" fill="#e6dc9d"/><path d="M250 229V108a85 85 0 00-170 0v121" fill="url(#arch)"/><path d="M224 229V112a59 59 0 00-118 0v117" fill="#16463d"/><path d="M139 232v-27h24v-27h24v-27h24v-27h24v108" fill="#f2ead6"/><path d="M139 232v-27h24v27m0-27v-27h24v54m0-54v-27h24v81m0-81v-27h24v108" stroke="#b5baa3" fill="none"/><path d="M67 226C68 192 52 176 62 146M64 190c-31-2-35-25-35-25 31-1 37 17 35 25M65 171c24-10 26-31 26-31-25 0-33 18-26 31M270 226c-2-31 20-52 13-91m-7 54c-25-9-31-26-31-26 28 0 34 20 31 26m7-26c23-10 26-30 26-30-28 2-34 18-26 30" fill="#92aa80" stroke="#92aa80" strokeWidth="2"/><ellipse cx="174" cy="233" rx="133" ry="5" fill="#0d352d" opacity=".3"/><path d="M304 84h10m-5-5v10M53 91h8m-4-4v8" stroke="#dcd9b3" strokeWidth="1.5"/></svg>}

function Progress({value}:{value:number}){return <div className="g-progress" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${value}%`}}/></div>}
function Empty({title,text,action,label='شروع کنیم'}:{title:string;text:string;action?:()=>void;label?:string}){return <div className="g-empty"><Sprout size={29}/><h3>{title}</h3><p>{text}</p>{action&&<button className="g-btn subtle" onClick={action}><Plus size={16}/>{label}</button>}</div>}

export default function GrowthApp(){
 const {data,ready,error,update,importData,exportData,clearError}=useGrowthData();
 const [tab,setTab]=useState<Tab>('home'),[config,setConfig]=useState<AppConfig>(defaultConfig),[today,setToday]=useState(dayKey()),[selectedDate,setSelectedDate]=useState(dayKey()),[edit,setEdit]=useState<Edit>(null),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[taskFilter,setTaskFilter]=useState('all'),[online,setOnline]=useState(true),[journalText,setJournalText]=useState(''),[gratitude,setGratitude]=useState(''),[mood,setMood]=useState(4),[resourceCategory,setResourceCategory]=useState('all'),[configState,setConfigState]=useState('محتوای همراه اپ');
 const dialog=useRef<HTMLDialogElement>(null), importInput=useRef<HTMLInputElement>(null), mainRef=useRef<HTMLElement>(null);
 const notify=useCallback((message:string)=>setNotice(message),[]);
 const go=useCallback((next:Tab)=>{triggerHaptic('selection');setTab(next);location.hash=next;setMenu(false);setQuery('');window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches||readPreferences().motion==='reduced'?'instant':'smooth'});requestAnimationFrame(()=>mainRef.current?.focus({preventScroll:true}));},[]);
 useEffect(()=>{if(ready&&(!data.profile.name||data.profile.name==='همراه روشنا')){const tgUser=getTelegramUser();if(tgUser){const name=[tgUser.first_name,tgUser.last_name].filter(Boolean).join(' ').trim();if(name)void update(d=>({...d,profile:{...d.profile,name}}));}}},[ready,data.profile.name,update]);
 useEffect(()=>{if(tab!=='home'){setupTelegramBackButton(true,()=>go('home'));}else{setupTelegramBackButton(false);}return()=>setupTelegramBackButton(false);},[tab,go]);
 useEffect(()=>{const change=()=>{const value=location.hash.slice(1);if([...navigation.map(x=>x.id),'settings'].includes(value))setTab(value as Tab);};if(!location.hash)location.hash=readPreferences().start;change();window.addEventListener('hashchange',change);const network=()=>setOnline(navigator.onLine);network();window.addEventListener('online',network);window.addEventListener('offline',network);const tick=setInterval(()=>setToday(dayKey()),30000);return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('online',network);window.removeEventListener('offline',network);clearInterval(tick)}},[]);
 useEffect(()=>{try{const cached=localStorage.getItem('roshana-config');if(cached){setConfig(appConfigSchema.parse(JSON.parse(cached)));setConfigState('آخرین محتوای دریافت‌شده')}}catch{}const controller=new AbortController();fetch('/api/config',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();const c=appConfigSchema.parse(await r.json());setConfig(c);setConfigState('به‌روز از سرور');try{localStorage.setItem('roshana-config',JSON.stringify(c))}catch{setConfigState('محتوا دریافت شد؛ ذخیره آفلاین محتوا ممکن نشد')}}).catch(()=>{});return()=>controller.abort()},[]);
 useEffect(()=>{if(edit)dialog.current?.showModal();else dialog.current?.close()},[edit]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5500);return()=>clearTimeout(timer)},[notice]);
 const dayTasks=data.tasks.filter(t=>t.date===today), doneTasks=dayTasks.filter(t=>t.done).length, doneHabits=data.habits.filter(h=>h.days.includes(today)).length;
 const weekly=lastDays(7,today), totalFocus=data.focus.filter(f=>f.date===today).reduce((s,f)=>s+f.minutes,0), weeklyFocus=data.focus.filter(f=>weekly.includes(f.date)).reduce((s,f)=>s+f.minutes,0);
 const weekCompleted=data.tasks.filter(t=>weekly.includes(t.date)&&t.done).length;
 const dailyProgress=percent(doneTasks+doneHabits,dayTasks.length+data.habits.length);
 const addTask=(date=selectedDate)=>{triggerHaptic('light');setEdit({type:'task',value:{id:uid(),title:'',date,time:'',priority:'medium',done:false}});};
 const addGoal=()=>{triggerHaptic('light');setEdit({type:'goal',value:{id:uid(),title:'',why:'',deadline:shiftDay(today,30),target:10,current:0,unit:'قدم'}});};
 const addHabit=()=>{triggerHaptic('light');setEdit({type:'habit',value:{id:uid(),title:'',days:[],color:'#477d60'}});};
 const toggleTask=(id:string)=>{triggerHaptic('medium');update(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)}));};
 const toggleHabit=(id:string,date:string)=>{triggerHaptic('medium');update(d=>({...d,habits:d.habits.map(h=>h.id===id?{...h,days:h.days.includes(date)?h.days.filter(k=>k!==date):[...h.days,date]}:h)}));};
 const remove=async(kind:'tasks'|'goals'|'habits'|'journal',id:string)=>{if(confirm('این مورد حذف شود؟')){if(!await update(d=>({...d,[kind]:d[kind].filter(x=>x.id!==id)})))return;setEdit(null);notify('مورد حذف شد.')}};
 async function saveEdit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!edit||edit.type==='resource')return;let saved=false;const f=new FormData(e.currentTarget),str=(k:string)=>String(f.get(k)||'').trim();if(edit.type==='task'){const item={...edit.value,title:str('title'),date:str('date'),time:str('time'),priority:str('priority') as Task['priority']};saved=await update(d=>({...d,tasks:[...d.tasks.filter(t=>t.id!==item.id),item]}))}if(edit.type==='goal'){const item={...edit.value,title:str('title'),why:str('why'),deadline:str('deadline'),target:Number(f.get('target')),current:Number(f.get('current')),unit:str('unit')};if(item.current>item.target){notify('پیشرفت نمی‌تواند بیشتر از مقدار هدف باشد.');return}saved=await update(d=>({...d,goals:[...d.goals.filter(t=>t.id!==item.id),item]}))}if(edit.type==='habit'){const item={...edit.value,title:str('title'),color:str('color')};saved=await update(d=>({...d,habits:[...d.habits.filter(t=>t.id!==item.id),item]}))}if(edit.type==='journal'){const item={...edit.value,text:str('text'),gratitude:str('gratitude'),mood:Number(f.get('mood'))};saved=await update(d=>({...d,journal:d.journal.map(t=>t.id===item.id?item:t)}))}if(saved){setEdit(null);notify('تغییرات ثبت شد.');}}
 function taskRow(t:Task){return <div className={`g-task ${t.done?'is-done':''}`} key={t.id}><button className="g-check" aria-label={`${t.done?'لغو انجام':'انجام'} ${t.title}`} aria-pressed={t.done} onClick={()=>toggleTask(t.id)}>{t.done&&<Check size={14}/>}</button><button className="g-task-title" onClick={()=>setEdit({type:'task',value:t})}>{t.title}<small>{t.time&&<><Clock3 size={11}/><span dir="ltr">{n(Number(t.time.slice(0,2)))}:{t.time.slice(3).replace(/\d/g,c=>'۰۱۲۳۴۵۶۷۸۹'[+c])}</span></>}</small></button><span className={`g-priority ${t.priority}`}>{priorityLabels[t.priority]}</span><button className="g-icon-btn" aria-label={`ویرایش ${t.title}`} onClick={()=>setEdit({type:'task',value:t})}><MoreHorizontal size={18}/></button></div>}
 function sectionHeading(title:string,sub:string,button?:React.ReactNode){return <div className="g-section-heading"><div><span className="g-eyebrow">فضای رشد تو</span><h1>{title}</h1><p>{sub}</p></div>{button}</div>}
 function wheelGraphic(){const points=domains.map((key,i)=>{const angle=(i*45-90)*Math.PI/180,r=(data.wheel[key]??0)*9;return `${120+Math.cos(angle)*r},${120+Math.sin(angle)*r}`}).join(' ');return <svg viewBox="0 0 240 240" className="g-wheel-chart" aria-label="نمودار ارزیابی شخصی حوزه‌های زندگی" role="img">{[18,36,54,72,90].map(r=><polygon key={r} points={domains.map((_,i)=>`${120+Math.cos((i*45-90)*Math.PI/180)*r},${120+Math.sin((i*45-90)*Math.PI/180)*r}`).join(' ')} fill="none" stroke="currentColor" opacity=".15"/>)}{domains.map((_,i)=><line key={i} x1={120} y1={120} x2={120+Math.cos((i*45-90)*Math.PI/180)*90} y2={120+Math.sin((i*45-90)*Math.PI/180)*90} stroke="currentColor" opacity=".1"/>)}<polygon points={points} fill="var(--accent)" fillOpacity=".3" stroke="var(--accent-readable)" strokeWidth="2"/>{domains.map((key,i)=><text key={key} x={120+Math.cos((i*45-90)*Math.PI/180)*108} y={123+Math.sin((i*45-90)*Math.PI/180)*108} textAnchor="middle" fill="currentColor" fontSize="9">{n(i+1)}</text>)}</svg>}
 if(!ready)return <main className="g-loading"><Flower2 size={46}/><h1>روشنا</h1><p>در حال باز کردن فضای شخصی تو…</p></main>;
 return <div className="g-app" dir="rtl">
  <a className="g-skip" href="#main-content">رفتن به محتوای اصلی</a>
  {menu&&<button className="g-scrim" aria-label="بستن فهرست" onClick={()=>setMenu(false)}/>}
  <aside className={`g-sidebar ${menu?'open':''}`}>
   <a href="#home" className="g-brand" onClick={()=>go('home')}><span className="g-brand-icon"><Flower2 size={27}/></span><span>{config.name}<small>زندگی، به سبک تو</small></span></a>
   <nav className="sx-sidebar-nav" aria-label="بخش‌های اپلیکیشن">{['زندگی من','روز من','رشد و آرامش','کشف و ارتباط'].map(group=><section key={group}><div className="g-sidebar-label">{group}</div>{navigation.filter(item=>destinations.find(d=>d.id===item.id)?.group===group).sort((a,b)=>a.id==='home'?-1:b.id==='home'?1:0).map(item=><button key={item.id} className={tab===item.id?'active':''} aria-current={tab===item.id?'page':undefined} onClick={()=>go(item.id)}><item.icon size={19}/>{item.id==='home'?'امروز من':item.label}{tab===item.id&&<span className="g-nav-dot"/>}</button>)}</section>)}</nav>
   <div className="g-sidebar-bottom"><div className="g-sidebar-note"><Sprout size={24}/><strong>رشد، یک مسیر است.</strong><p>هر قدم کوچک تو، ارزشمند است.</p><span>با ریتم خودت ادامه بده</span></div><button className={`g-settings-link ${tab==='settings'?'active':''}`} onClick={()=>go('settings')}><Settings size={19}/>تنظیمات و پشتیبان</button><div className="g-user"><span className="g-avatar">{data.profile.name?.charAt(0)||'م'}</span><div><strong>{data.profile.name||'همراه روشنا'}</strong><small>فضای امنِ فکرهای تو</small></div><ShieldCheck size={18}/></div></div>
  </aside>
  <div className="g-workspace">
    <header className="g-topbar"><div className="g-top-title"><button className="g-icon-btn g-mobile-menu" aria-label="باز کردن فهرست" onClick={()=>setMenu(true)}><Menu size={22}/></button><span>{tab==='settings'?'تنظیمات':navigation.find(t=>t.id===tab)?.label}</span><span className="g-top-divider"/><span className="g-date"><CalendarDays size={15}/>{faDate(today,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span></div><div className="g-top-actions"><GlobalSearch data={data} config={config} go={go} onOpen={(kind,id)=>{if(kind==='tasks'){const value=data.tasks.find(t=>t.id===id);if(value){go('planner');setSelectedDate(value.date);setEdit({type:'task',value})}}else if(kind==='goals'){const value=data.goals.find(t=>t.id===id);if(value){go('goals');setEdit({type:'goal',value})}}else if(kind==='journal'){const value=data.journal.find(t=>t.id===id);if(value){go('journal');setEdit({type:'journal',value})}}else if(kind==='projects'){go('projects');}else if(kind==='decisions'){go('reflection');}else if(kind==='journeys'){go('journeys');}else{const value=config.resources.find(t=>t.id===id);if(value){go('library');setEdit({type:'resource',value})}}}}/><NotificationCenter go={go}/><ThemePicker compact/><span className={`g-network ${online?'':'offline'}`}><span/>{online?'فضای شخصی تو':'در حالت آفلاین'}</span><button className="g-icon-btn" aria-label="راهنمای نصب و پشتیبان" onClick={()=>go('settings')}><CircleHelp size={20}/></button><button className="g-avatar small" aria-label="تنظیمات پروفایل" onClick={()=>go('settings')}>{data.profile.name?.charAt(0)||'م'}</button></div></header>
   {error&&<div className="g-alert" role="alert"><ShieldCheck size={19}/><span>{error}</span><button onClick={exportData}>دانلود پشتیبان</button><button className="g-icon-btn" aria-label="بستن پیام" onClick={clearError}><X size={17}/></button></div>}
   <main className="g-main" id="main-content" ref={mainRef} tabIndex={-1}>
   <UsageSignal tab={tab}/>
   {tab==='home'&&<ModuleBoundary key="today"><Today data={data} update={update} go={go} notify={notify} today={today}/></ModuleBoundary>}
   {tab==='journeys'&&<ModuleBoundary key="journeys"><Journeys data={data} update={update} go={go} notify={notify} today={today}/></ModuleBoundary>}
   {tab==='projects'&&<ModuleBoundary key="projects"><Projects data={data} update={update} go={go} notify={notify} today={today}/></ModuleBoundary>}
   {tab==='companion'&&<ModuleBoundary key="companion"><Companion data={data} update={update} go={go} notify={notify} today={today}/></ModuleBoundary>}
   {tab==='reflection'&&<ModuleBoundary key="reflection"><Reflection data={data} update={update} go={go} notify={notify} today={today}/></ModuleBoundary>}
   {tab==='trust'&&<ModuleBoundary key="trust"><Trust data={data} update={update} go={go} notify={notify} today={today}/></ModuleBoundary>}
   {tab==='community'&&<ModuleBoundary key="community"><CommunityHub/></ModuleBoundary>}
   {tab==='markets'&&<ModuleBoundary key="markets"><MarketHub/></ModuleBoundary>}
   {tab==='tv'&&<ModuleBoundary key="tv"><LiveTV/></ModuleBoundary>}
   {tab==='language'&&<ModuleBoundary key="language"><LanguageHub/></ModuleBoundary>}
   {tab==='meditation'&&<ModuleBoundary key="meditation"><MeditationHub/></ModuleBoundary>}
   {tab==='workout'&&<ModuleBoundary key="workout"><WorkoutHub/></ModuleBoundary>}
   {tab==='self-discovery'&&<ModuleBoundary key="self-discovery"><SelfDiscoveryHub/></ModuleBoundary>}
   {tab==='games'&&<ModuleBoundary key="games"><GameCenter/></ModuleBoundary>}
   {tab==='mentor'&&<ModuleBoundary key="mentor"><AiMentor data={data} go={go} notify={notify}/></ModuleBoundary>}
   {tab==='radio'&&<ModuleBoundary key="radio"><RadioHub/></ModuleBoundary>}
   {tab==='challenges'&&<ModuleBoundary key="challenges"><GamificationHub data={data} notify={notify}/></ModuleBoundary>}
   {tab==='gadgets'&&<Gadgets data={data} update={update} notify={notify}/>}
   {tab==='overview'&&<>
    <div className="g-greeting"><div><span className="g-eyebrow">یک روز تازه، یک فرصت تازه</span><h1>سلام{data.profile.name?` ${data.profile.name}`:''}، به خودت خوش اومدی <span className="g-wave">☀</span></h1><p>لازم نیست همه‌چیز را تغییر بدهی؛ امروز فقط یک قدم کوچک بردار.</p></div><button className="g-btn" onClick={()=>addTask(today)}><Plus size={17}/>برنامه جدید</button></div>
    <FavoritesRail go={go}/><DiscoveryDeck go={go}/><DashboardShortcuts go={go}/>
    <div className="g-dashboard-grid"><div className="g-dashboard-main">
     <section className="g-hero"><div className="g-hero-content"><span><span className="g-tiny-star">✦</span> هر روز، کمی نزدیک‌تر به خودت</span><h2>نسخه بهتر تو،<br/>از همین امروز شروع می‌شود.</h2><p>{data.profile.intention||config.tagline}</p><button className="g-btn hero" onClick={()=>go('planner')}>روزت را آگاهانه بساز <ArrowLeft size={17}/></button></div><GrowthArt/></section>
     <div className="g-stats"><article><span className="g-stat-icon mint"><Check size={20}/></span><div><small>کارهای انجام‌شده</small><strong>{n(doneTasks)} <em>از {n(dayTasks.length)}</em></strong></div><span className="g-stat-note">امروز</span></article><article><span className="g-stat-icon lilac"><Focus size={20}/></span><div><small>زمان برای تمرکز</small><strong>{n(totalFocus)} <em>دقیقه</em></strong></div><span className="g-stat-note">امروز</span></article><article><span className="g-stat-icon peach"><Flame size={20}/></span><div><small>عادت‌های امروز</small><strong>{n(doneHabits)} <em>از {n(data.habits.length)}</em></strong></div><span className="g-stat-note">قدم کوچک</span></article></div>
     <section className="g-card"><div className="g-card-heading"><h2><CalendarDays size={19}/> برنامه امروز</h2><button className="g-text-btn" onClick={()=>go('planner')}>همه برنامه‌ها <ChevronLeft size={15}/></button></div>{dayTasks.length?<><div className="g-mini-progress"><span>{n(doneTasks)} کار از {n(dayTasks.length)} کار انجام شده</span><span>{n(percent(doneTasks,dayTasks.length))}٪</span></div><Progress value={percent(doneTasks,dayTasks.length)}/><div className="g-task-list">{dayTasks.slice(0,4).map(taskRow)}</div></>:<Empty title="جای اولین قدم امروزت خالی است" text="یک کار کوچک و شدنی انتخاب کن؛ مثلاً ۱۰ دقیقه مطالعه." action={()=>addTask(today)} label="افزودن اولین برنامه"/>}<button className="g-add-row" onClick={()=>addTask(today)}><Plus size={16}/>یک کار تازه اضافه کن</button></section>
     <section className="g-card"><div className="g-card-heading"><h2><Flame size={19}/> کوچک، اما پیوسته</h2><button className="g-text-btn" onClick={()=>go('habits')}>عادت‌های من <ChevronLeft size={15}/></button></div>{data.habits.length?<div className="g-home-habits">{data.habits.slice(0,3).map(h=><button key={h.id} className={h.days.includes(today)?'checked':''} onClick={()=>toggleHabit(h.id,today)} aria-pressed={h.days.includes(today)}><span className="g-habit-mark">{h.days.includes(today)?<Check size={19}/>:<Leaf size={19}/>}</span><strong>{h.title}</strong><small>{n(habitStreak(h.days,today))} روز پیوستگی</small><span className="g-check">{h.days.includes(today)&&<Check size={13}/>}</span></button>)}</div>:<div className="g-habit-suggestions">{['۱۰ دقیقه مطالعه','یک لیوان آب بیشتر','۵ دقیقه سکوت'].map(title=><button key={title} onClick={async()=>{if(!await update(d=>({...d,habits:[...d.habits,{id:uid(),title,days:[],color:'#477d60'}]})))return;notify('عادت به برنامه تو اضافه شد.')}}><Leaf size={17}/>{title}<Plus size={15}/></button>)}</div>}</section>
      <button className="g-lang-card" onClick={()=>go('language')} aria-label="Ø¨Ø®Ø´ Ø²Ø¨Ø§Ù†â€ŒØ¢Ù…ÙˆØ²">
        <span className="g-lang-card-flag">ðŸ‡¬ðŸ‡§</span>
        <span className="g-lang-card-body">
          <small>DAILY ENGLISH Â· Ø¢Ù…ÙˆØ²Ø´ Ø±ÙˆØ²Ø§Ù†Ù‡</small>
          <strong>Ø§Ù…Ø±ÙˆØ² Ú†Ù†Ø¯ Ú©Ù„Ù…Ù‡ Ø§Ù†Ú¯Ù„ÛŒØ³ÛŒ ÛŒØ§Ø¯ Ø¨Ú¯ÛŒØ±ÛŒØ¯</strong>
          <span>ÙˆØ§Ú˜Ú¯Ø§Ù† Â· Ù…Ú©Ø§Ù„Ù…Ù‡ Â· Ú¯Ø±Ø§Ù…Ø± Â· Ø¢Ø²Ù…ÙˆÙ†</span>
        </span>
        <span className="g-lang-card-arrow"><ArrowLeft size={18}/></span>
      </button>
     <section className="g-reflection-banner"><span className="g-reflection-symbol">“</span><div><small>مکثی برای خودت</small><h3>{prompts[new Date(`${today}T12:00:00`).getDay()]}</h3><button className="g-text-btn" onClick={()=>go('journal')}>چند خط برای خودم بنویسم <ArrowLeft size={15}/></button></div><BookOpen size={55}/></section>
    </div><aside className="g-dashboard-aside">
     <section className="g-card g-day-card"><div className="g-card-heading"><h2>امروزِ من</h2><Sparkles size={18}/></div><div className="g-day-ring" style={{'--progress':`${dailyProgress*3.6}deg`} as React.CSSProperties}><div><strong>{n(dailyProgress)}<small>٪</small></strong><span>قدم‌های امروز</span></div></div><p>{dailyProgress===100?'به خودت بابت قدم‌های امروزت افتخار کن.':'با یک قدم کوچک، دایره امروزت را کامل‌تر کن.'}</p><div className="g-day-week">{weekly.map(k=><span key={k} className={k===today?'today':data.tasks.some(t=>t.date===k&&t.done)||data.habits.some(h=>h.days.includes(k))?'has-activity':''}><small>{faDate(k,{weekday:'narrow'})}</small><b>{faDate(k,{day:'numeric'})}</b></span>)}</div></section>
     <section className="g-card g-mood-card"><h2>امروز چطوری؟</h2><p>همین لحظه، بدون قضاوت.</p><div className="g-moods">{moods.map((m,i)=><button key={m.label} aria-label={m.label} title={m.label} className={mood===i+1?'selected':''} onClick={()=>{setMood(i+1);go('journal')}}><span>{m.emoji}</span></button>)}</div><small>احساست را در دفتر خودشناسی ثبت کن.</small></section>
     <section className="g-focus-card"><span className="g-focus-icon"><Focus size={24}/></span><h2>۲۵ دقیقه، فقط برای یک کار</h2><p>حواس‌پرتی‌ها را کنار بگذار.<br/>یک قدم به هدفت نزدیک‌تر شو.</p><button className="g-btn" onClick={()=>go('focus')}>شروع یک تمرکز <ArrowLeft size={16}/></button></section>
     <div className="g-privacy-note"><ShieldCheck size={16}/><p>یادداشت‌ها و برنامه‌های تو روی همین دستگاه می‌مانند.</p></div>
    </aside></div>
   </>}

   {tab==='planner'&&<>{sectionHeading('روزت را با قصد شروع کن.','جای کارهای مهم، استراحت و زندگی را کنار هم باز کن.',<button className="g-btn primary" onClick={()=>addTask()}><Plus size={18}/>کار جدید</button>)}<div className="g-planner-toolbar g-card"><div className="g-date-picker"><button className="g-icon-btn" aria-label="روز قبل" onClick={()=>setSelectedDate(shiftDay(selectedDate,-1))}><ChevronRight size={19}/></button><label><span>{faDate(selectedDate,{weekday:'long',day:'numeric',month:'long'})}</span><input type="date" aria-label="انتخاب تاریخ برنامه" value={selectedDate} onChange={e=>e.target.value&&setSelectedDate(e.target.value)}/></label><button className="g-icon-btn" aria-label="روز بعد" onClick={()=>setSelectedDate(shiftDay(selectedDate,1))}><ChevronLeft size={19}/></button><button className="g-text-btn" onClick={()=>setSelectedDate(today)}>امروز</button></div><div className="g-search"><Search size={17}/><input placeholder="جست‌وجو در کارهای این روز…" aria-label="جست‌وجوی برنامه" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="g-week-strip">{lastDays(7,shiftDay(selectedDate,3)).map(k=><button key={k} className={k===selectedDate?'selected':''} onClick={()=>setSelectedDate(k)}><span>{faDate(k,{weekday:'short'})}</span><strong>{faDate(k,{day:'numeric'})}</strong><small>{n(data.tasks.filter(t=>t.date===k).length)} کار</small></button>)}</div><section className="g-card"><div className="g-card-heading"><h2>کارهای این روز</h2><div className="g-tabs">{[['all','همه'],['open','انجام‌نشده'],['done','انجام‌شده']].map(([id,label])=><button key={id} className={taskFilter===id?'selected':''} onClick={()=>setTaskFilter(id)}>{label}</button>)}</div></div>{data.tasks.filter(t=>t.date===selectedDate&&t.title.includes(query)&&(taskFilter==='all'||t.done===(taskFilter==='done'))).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99')).map(taskRow)}{!data.tasks.some(t=>t.date===selectedDate)&&<Empty title="این روز هنوز یک صفحه سفید است" text="با مهم‌ترین کار شروع کن و برای استراحت هم وقت بگذار." action={()=>addTask()}/>}<button className="g-add-row" onClick={()=>addTask()}><Plus size={17}/>اضافه کردن کار</button></section><p className="g-footnote"><Clock3 size={15}/>یادآور کارهای ساعت‌دار از تنظیمات فعال می‌شود؛ دریافت در زمان بسته‌بودن کامل اپ فعال نیست.</p></>}

   {tab==='goals'&&<>{sectionHeading('مقصدت را روشن کن.','یک هدف معنادار، با قدم‌هایی که می‌توانی اندازه بگیری.',<button className="g-btn primary" onClick={addGoal}><Plus size={18}/>هدف جدید</button>)}{!data.goals.length?<section className="g-card"><Empty title="دوست داری به چه چیزی نزدیک‌تر شوی؟" text="مثلاً خواندن ۱۲ کتاب؛ یک مقصد مشخص، یک چرایی شخصی، و یک زمان واقع‌بینانه." action={addGoal} label="ساخت اولین هدف"/></section>:<div className="g-goal-grid">{data.goals.map(g=><article key={g.id} className="g-card g-goal-card"><div className="g-card-heading"><span className="g-stat-icon mint"><Target size={22}/></span><button className="g-icon-btn" aria-label={`ویرایش ${g.title}`} onClick={()=>setEdit({type:'goal',value:g})}><Pencil size={17}/></button></div><span className="g-tag">{g.current>=g.target?'به مقصد رسیدم':g.deadline&&g.deadline<today?'وقت بازنگری':'در مسیر رشد'}</span><h2>{g.title}</h2><p>{g.why||'هر قدم، تو را به این هدف نزدیک‌تر می‌کند.'}</p><div className="g-mini-progress"><span>{n(g.current)} از {n(g.target)} {g.unit}</span><b>{n(percent(g.current,g.target))}٪</b></div><Progress value={percent(g.current,g.target)}/><footer><span><CalendarDays size={14}/>{g.deadline?faDate(g.deadline):'بدون موعد'}</span><button className="g-text-btn" onClick={()=>setEdit({type:'goal',value:g})}>ثبت پیشرفت <Plus size={14}/></button></footer></article>)}</div>}</>}

   {tab==='habits'&&<>{sectionHeading('تغییرهای کوچک، اثرهای ماندگار.','پیوستگی مهم‌تر از بی‌نقص بودن است. روزهای گذشته را هم می‌توانی ثبت کنی.',<button className="g-btn primary" onClick={addHabit}><Plus size={18}/>عادت جدید</button>)}<section className="g-card g-habit-table"><div className="g-habit-table-head"><h2>هفت روزِ کوچک تو</h2><span>برای ثبت، روی هر روز بزن</span></div>{!data.habits.length?<Empty title="یک عادت آسان انتخاب کن" text="از کاری شروع کن که حتی در روزهای شلوغ هم شدنی است." action={addHabit}/>:data.habits.map(h=><div className="g-habit-row" key={h.id}><div className="g-habit-info"><span className="g-stat-icon" style={{color:h.color,background:`${h.color}18`}}><Leaf size={22}/></span><div><h3>{h.title}</h3><small><Flame size={13}/>{n(habitStreak(h.days,today))} روز پیوستگی · {n(h.days.length)} بار ثبت</small></div></div><div className="g-habit-days">{weekly.map(k=><div key={k}><small>{faDate(k,{weekday:'short'})}</small><button className={h.days.includes(k)?'done':''} aria-pressed={h.days.includes(k)} aria-label={`${h.title}، ${faDate(k)}`} onClick={()=>toggleHabit(h.id,k)}>{h.days.includes(k)?<Check size={18}/>:faDate(k,{day:'numeric'})}</button></div>)}</div><button className="g-icon-btn" aria-label={`ویرایش ${h.title}`} onClick={()=>setEdit({type:'habit',value:h})}><MoreHorizontal size={21}/></button></div>)}</section><div className="g-callout"><Leaf size={24}/><div><strong>یک روز جا افتادن، پایان مسیر نیست.</strong><p>کوچک‌ترش کن، به یک کار روزمره وصلش کن و دوباره شروع کن.</p></div></div></>}

   {tab==='journal'&&<>{sectionHeading('جایی برای شنیدنِ خودت.','چند خط صادقانه بنویس. اینجا قرار نیست چیزی را ثابت کنی.')}<div className="g-journal-grid"><section className="g-card"><div className="g-card-heading"><h2>حالِ امروز من</h2><span className="g-tag">{faDate(today)}</span></div><form onSubmit={async e=>{e.preventDefault();if(!journalText.trim()&&!gratitude.trim()){notify('یک جمله درباره خودت یا قدردانی‌ات بنویس.');return}if(!await update(d=>({...d,journal:[{id:uid(),date:today,mood,text:journalText.trim(),gratitude:gratitude.trim()},...d.journal]})))return;setJournalText('');setGratitude('');notify('یادداشتت در فضای شخصی ثبت شد.')}}><div className="g-moods with-label">{moods.map((m,i)=><button type="button" key={m.label} className={mood===i+1?'selected':''} onClick={()=>setMood(i+1)} aria-pressed={mood===i+1}><span>{m.emoji}</span><small>{m.label}</small></button>)}</div><label className="g-field">چه چیزی در ذهن تو می‌گذرد؟<textarea rows={7} maxLength={20000} placeholder="می‌توانم از همین لحظه شروع کنم…" value={journalText} onChange={e=>setJournalText(e.target.value)}/></label><label className="g-field">امروز قدردانِ چه چیزی هستی؟<textarea rows={2} maxLength={4000} placeholder="حتی یک اتفاق خیلی کوچک…" value={gratitude} onChange={e=>setGratitude(e.target.value)}/></label><button className="g-btn primary" type="submit"><Check size={17}/>ثبت در دفتر من</button></form></section><aside><div className="g-card g-prompt-card"><Sparkles size={24}/><h2>پرسش امروز</h2><p>{prompts[new Date(`${today}T12:00:00`).getDay()]}</p><button className="g-text-btn" onClick={()=>setJournalText(t=>t+(t?'\n\n':'')+prompts[new Date(`${today}T12:00:00`).getDay()]+'\n')}>شروع با این پرسش <ArrowLeft size={15}/></button></div><div className="g-callout"><ShieldCheck size={23}/><p>نوشته‌ها روی این مرورگر ذخیره می‌شوند. برای نگهداری بلندمدت، از تنظیمات فایل پشتیبان بگیر.</p></div></aside></div><section className="g-card g-journal-history"><div className="g-card-heading"><h2>صفحه‌های گذشته من</h2><span>{n(data.journal.length)} یادداشت</span></div>{!data.journal.length?<Empty title="این دفتر، از تو شروع می‌شود" text="اولین یادداشتت را در فرم بالا ثبت کن."/>:data.journal.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(j=><article key={j.id}><div><span className="g-journal-emoji">{moods[j.mood-1]?.emoji}</span><strong>{faDate(j.date,{day:'numeric',month:'long',year:'numeric'})}</strong><span className="g-tag">{moods[j.mood-1]?.label}</span><button className="g-icon-btn" aria-label="ویرایش یادداشت" onClick={()=>setEdit({type:'journal',value:j})}><Pencil size={16}/></button></div><p>{j.text}</p>{j.gratitude&&<small><Heart size={14}/>قدردانِ {j.gratitude}</small>}</article>)}</section></>}

   {tab==='wheel'&&<>{sectionHeading('تصویر امروزِ زندگی تو.','رضایتت از هر حوزه را از ۱ تا ۱۰ ثبت کن. این یک تأمل شخصی است، نه آزمون روان‌شناسی.')}<div className="g-wheel-grid"><section className="g-card"><h2>چرخه زندگی</h2>{wheelGraphic()}<p className="g-center-text">قرار نیست همه امتیازها ۱۰ باشند.<br/>کدام بخش این روزها به توجه بیشتری نیاز دارد؟</p><span className="g-tag">{n(domains.filter(k=>data.wheel[k]!==undefined).length)} از ۸ حوزه ارزیابی شده</span></section><section className="g-card">{domains.map((key,i)=><label className="g-wheel-slider" key={key}><span><b>{n(i+1)}. {key}</b><strong>{data.wheel[key]===undefined?'ثبت نشده':n(data.wheel[key])+' از ۱۰'}</strong></span><input type="range" min={1} max={10} step={1} value={data.wheel[key]??5} aria-label={`رضایت از ${key}`} onChange={e=>update(d=>({...d,wheel:{...d.wheel,[key]:Number(e.target.value)}}))}/>{data.wheel[key]===undefined&&<button type="button" className="g-text-btn" onClick={()=>update(d=>({...d,wheel:{...d.wheel,[key]:5}}))}>ثبت امتیاز ۵</button>}</label>)}</section></div><div className="g-callout"><Target size={24}/><div><strong>از شناخت به یک قدم عملی</strong><p>برای حوزه‌ای که می‌خواهی بهتر شود، یک هدف کوچک بساز.</p></div><button className="g-btn" onClick={addGoal}>ساخت هدف <ArrowLeft size={16}/></button></div></>}

   <div hidden={tab!=='focus'}>{tab==='focus'&&sectionHeading('حضور کامل، در یک کار.','یک بازه انتخاب کن، کارها را ساده کن و به همین لحظه برگرد.')}<FocusTimer active={tab==='focus'} update={update} notify={notify} today={today}/>{tab==='focus'&&<section className="g-card g-focus-history"><h2>تمرکزهای اخیر</h2>{data.focus.length?<div className="g-session-list">{data.focus.slice(-12).reverse().map(f=><div key={f.id}><Focus size={18}/><strong>{n(f.minutes)} دقیقه تمرکز</strong><span>{faDate(f.date)}</span></div>)}</div>:<p>بعد از پایان اولین بازه، زمان تمرکزت اینجا ثبت می‌شود.</p>}</section>}</div>

   {tab==='insights'&&<ModuleBoundary key="insights"><MonthlyAnalytics data={data} go={go} notify={notify} today={today}/></ModuleBoundary>}

   {tab==='library'&&<>{sectionHeading('کمی یاد بگیر، کمی تجربه کن.','تمرین‌های کوتاه برای شناخت خودت و ساختن روزهای بهتر.')}<div className="g-library-toolbar"><div className="g-tabs">{[['all','همه تمرین‌ها'],['awareness','خودشناسی'],['planning','برنامه‌ریزی'],['habits','عادت‌سازی']].map(([id,label])=><button key={id} className={resourceCategory===id?'selected':''} onClick={()=>setResourceCategory(id)}>{label}</button>)}</div><span className="g-footnote">{configState}</span></div>{config.announcement&&<div className="g-callout"><Sparkles size={20}/><p>{config.announcement}</p></div>}<div className="g-resource-grid">{config.resources.filter(r=>r.published&&(resourceCategory==='all'||r.category===resourceCategory)).map((r,i)=><article className="g-card g-resource" key={r.id}><button className={`g-resource-art art-${i%3}`} aria-label={`خواندن ${r.title}`} onClick={()=>setEdit({type:'resource',value:r})}>{r.category==='awareness'?<Flower2 size={68} strokeWidth={1}/>:r.category==='planning'?<CalendarDays size={68} strokeWidth={1}/>:<Sprout size={68} strokeWidth={1}/>}<span>۰{n(i+1)}</span><span className="g-resource-orbit"/></button><div className="g-resource-meta"><span>{r.category==='awareness'?'خودشناسی':r.category==='planning'?'برنامه‌ریزی':'عادت‌سازی'}</span><span><Clock3 size={12}/>{n(r.minutes)} دقیقه</span></div><h2>{r.title}</h2><p>{r.description}</p><button className="g-text-btn" onClick={()=>setEdit({type:'resource',value:r})}>شروع تمرین <ArrowLeft size={15}/></button></article>)}</div><p className="g-footnote">متن تمرین‌ها پس از دریافت، آفلاین در دسترس است؛ پیوندهای بیرونی به اینترنت نیاز دارند.</p></>}

   {tab==='settings'&&<>{sectionHeading('این فضا را برای خودت بساز.','تنظیمات، نصب اپلیکیشن و نگهداری امن‌تر از داده‌هایت.')}<div className="g-settings-grid"><section className="g-card"><h2>درباره تو</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!await update(d=>({...d,profile:{name:String(f.get('name')).trim(),intention:String(f.get('intention')).trim()}})))return;notify('پروفایل به‌روز شد.')}}><label className="g-field">دوست داری با چه اسمی صدایت کنیم؟<input name="name" maxLength={60} defaultValue={data.profile.name} placeholder="نام یا نام مستعار"/></label><label className="g-field">این روزها می‌خواهم…<textarea name="intention" rows={3} maxLength={500} defaultValue={data.profile.intention} placeholder="مثلاً با آرامش و آگاهی بیشتری زندگی کنم."/></label><button className="g-btn primary">ذخیره پروفایل</button></form><ThemePicker/></section><section className="g-card"><h2><ShieldCheck size={20}/> پشتیبانِ مسیر تو</h2><p>برنامه‌ها، هدف‌ها، عادت‌ها و نوشته‌های این بخش فقط در همین مرورگر هستند و به سرور مدیر ارسال نمی‌شوند. حساب گفتگو، پیام‌ها، دوستان و بازی آنلاین برای کارکرد بین دستگاه‌ها روی سرور ذخیره می‌شوند.</p><div className="g-backup-actions"><button className="g-btn primary" onClick={()=>{if(!exportData())return;notify('فایل پشتیبان برای دانلود آماده شد.')}}><Download size={18}/>دانلود پشتیبان JSON</button><button className="g-btn" onClick={()=>importInput.current?.click()}><Upload size={18}/>بازیابی از فایل</button></div><input ref={importInput} type="file" accept=".json,application/json" className="g-file-hidden" aria-label="فایل پشتیبان" onChange={async e=>{const file=e.target.files?.[0];e.currentTarget.value='';if(!file)return;if(file.size>10*1024*1024){notify('فایل باید کمتر از ۱۰ مگابایت باشد.');return}if(!confirm('بازیابی، اطلاعات فعلی این دستگاه را جایگزین می‌کند. ابتدا پشتیبان بگیرید. ادامه می‌دهید؟'))return;try{await importData(await file.text());notify('پشتیبان با موفقیت بازیابی شد.')}catch(err){notify(err instanceof Error?err.message:'فایل پشتیبان معتبر نیست.')}}}/><div className="g-backup-tip"><BookOpen size={20}/><p>برای انتقال داده‌های شخصی به دستگاه دیگر، فایل پشتیبان را آنجا بازیابی کن. این فایل شامل یادداشت‌هایت است و رمزگذاری نشده؛ در جای خصوصی نگهش دار.</p></div><button className="g-text-btn danger" onClick={async()=>{if(confirm('همه داده‌های شخصی پاک شوند؟ قبل از ادامه پشتیبان بگیرید.')){if(!exportData())return;if(!await update(()=>emptyData()))return;try{localStorage.removeItem('roshana-timer')}catch{}location.reload()}}}><Trash2 size={15}/>پاک‌کردن داده‌های شخصی این دستگاه</button></section></div><Personalization notify={notify}/><section className="g-card g-about-card"><Flower2 size={29}/><div><h2>{config.name}، همراه قدم‌های کوچک تو</h2><p>نسخه ۲.۰ · رشد، ارتباط، آگاهی و بازی · آمار استفاده فقط با انتخاب تو</p></div><a className="g-btn" href="/admin">پنل مدیریت <ArrowLeft size={15}/></a></section></>}
   <div hidden={tab!=='settings'}><ReminderSettings data={data} update={update} notify={notify}/></div>
   <div hidden={tab!=='settings'} className="g-pwa-wrap"><PwaManager/></div>
   <footer className="g-footer"><span><Flower2 size={14}/>{config.name} · هر روز، کمی نزدیک‌تر به خودت</span><span>با ریتم خودت رشد کن.</span></footer>
   </main>
  </div>
  <nav className="g-bottom-nav" aria-label="ناوبری موبایل">{(['home','journeys','companion','community'] as const).map(id=>{const item=navigation.find(x=>x.id===id)!;return <button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>go(id)}><item.icon size={21}/><span>{id==='home'?'امروز':id==='journeys'?'مسیرها':item.label}</span></button>})}<button onClick={()=>setMenu(true)}><Menu size={21}/><span>بیشتر</span></button></nav>
  <Onboarding data={data} update={update} go={go}/>
  {notice&&<div className="g-toast" role="status"><Check size={18}/>{notice}<button className="g-icon-btn" onClick={()=>setNotice('')} aria-label="بستن اعلان"><X size={16}/></button></div>}
  <dialog ref={dialog} className="g-dialog" onCancel={()=>setEdit(null)} onClick={e=>{if(e.target===e.currentTarget)setEdit(null)}}>{edit&&<><div className="g-dialog-header"><h2>{edit.type==='task'?'یک قدم در برنامه تو':edit.type==='goal'?'هدف و پیشرفت تو':edit.type==='habit'?'یک عادت کوچک':edit.type==='journal'?'بازخوانی یادداشت':edit.value.title}</h2><button className="g-icon-btn" aria-label="بستن پنجره" onClick={()=>setEdit(null)}><X size={20}/></button></div>{edit.type==='resource'?<div className="g-resource-body"><span className="g-tag">{n(edit.value.minutes)} دقیقه برای خودت</span><p>{edit.value.body}</p>{edit.value.url&&<a className="g-btn" href={edit.value.url} target="_blank" rel="noopener noreferrer">منبع تکمیلی · آنلاین <ArrowLeft size={16}/></a>}<button className="g-btn primary" onClick={()=>{setJournalText(edit.value.title+'\n\n');setEdit(null);go('journal')}}>تجربه‌ام را بنویسم <Pencil size={16}/></button></div>:<form onSubmit={saveEdit} key={edit.value.id}>
   {(edit.type==='task'||edit.type==='goal'||edit.type==='habit')&&<label className="g-field">عنوان<input name="title" required autoFocus maxLength={200} defaultValue={edit.value.title} placeholder={edit.type==='task'?'مثلاً ۲۰ دقیقه پیاده‌روی':edit.type==='goal'?'مثلاً خواندن ۱۲ کتاب':'مثلاً ۵ دقیقه نوشتن'}/></label>}
   {edit.type==='task'&&<><div className="g-form-row"><label className="g-field">تاریخ<input name="date" type="date" required defaultValue={edit.value.date}/></label><label className="g-field">ساعت (اختیاری)<input name="time" type="time" defaultValue={edit.value.time}/></label></div><label className="g-field">اولویت<select name="priority" defaultValue={edit.value.priority}><option value="high">مهم</option><option value="medium">معمولی</option><option value="low">آرام و پیوسته</option></select></label></>}
   {edit.type==='goal'&&<><label className="g-field">چرا این هدف برای من مهم است؟<textarea name="why" rows={3} maxLength={2000} defaultValue={edit.value.why}/></label><div className="g-form-row"><label className="g-field">مقدار هدف<input name="target" type="number" min={1} max={1000000} required defaultValue={edit.value.target}/></label><label className="g-field">پیشرفت فعلی<input name="current" type="number" min={0} max={1000000} required defaultValue={edit.value.current}/></label></div><div className="g-form-row"><label className="g-field">واحد اندازه‌گیری<input name="unit" maxLength={40} required defaultValue={edit.value.unit}/></label><label className="g-field">زمان هدف<input name="deadline" type="date" required defaultValue={edit.value.deadline}/></label></div></>}
   {edit.type==='habit'&&<><label className="g-field">رنگ عادت<input name="color" type="color" defaultValue={edit.value.color}/></label><p className="g-footnote">عادت‌ها روزانه‌اند؛ ثبت روزهای گذشته از جدول هفتگی ممکن است.</p></>}
   {edit.type==='journal'&&<><label className="g-field">حال من<select name="mood" defaultValue={edit.value.mood}>{moods.map((m,i)=><option key={m.label} value={i+1}>{m.label}</option>)}</select></label><label className="g-field">یادداشت<textarea name="text" rows={7} maxLength={20000} defaultValue={edit.value.text}/></label><label className="g-field">قدردانی<textarea name="gratitude" rows={3} maxLength={4000} defaultValue={edit.value.gratitude}/></label></>}
   <div className="g-dialog-actions"><button className="g-btn primary" type="submit"><Check size={17}/>ذخیره</button><button className="g-btn" type="button" onClick={()=>setEdit(null)}>انصراف</button>{((edit.type==='task'&&data.tasks.some(x=>x.id===edit.value.id))||(edit.type==='goal'&&data.goals.some(x=>x.id===edit.value.id))||(edit.type==='habit'&&data.habits.some(x=>x.id===edit.value.id))||edit.type==='journal')&&<button className="g-icon-btn danger" type="button" aria-label="حذف این مورد" onClick={()=>remove(edit.type==='task'?'tasks':edit.type==='goal'?'goals':edit.type==='habit'?'habits':'journal',edit.value.id)}><Trash2 size={19}/></button>}</div>
  </form>}</>}</dialog>
 </div>;
}

type TimerState={id:string;minutes:number;remaining:number;endsAt:number|null;mode:'work'|'rest'};
function FocusTimer({active,update,notify,today}:{active:boolean;update:(f:(d:GrowthData)=>GrowthData)=>Promise<boolean>;notify:(s:string)=>void;today:string}){
 const completing=useRef<string|null>(null);
 const [timer,setTimer]=useState<TimerState>({id:'',minutes:25,remaining:1500,endsAt:null,mode:'work'}),[now,setNow]=useState(Date.now()),[loaded,setLoaded]=useState(false);
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('roshana-timer')||'null');if(raw&&typeof raw.id==='string'&&[5,25,50].includes(raw.minutes)&&typeof raw.remaining==='number'&&raw.remaining>=0&&raw.remaining<=3000&&(raw.endsAt===null||typeof raw.endsAt==='number')&&['work','rest'].includes(raw.mode))setTimer(raw)}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem('roshana-timer',JSON.stringify(timer))}catch{notify('وضعیت تایمر پس از بستن صفحه قابل بازیابی نیست.')}},[timer,loaded,notify]);
 useEffect(()=>{if(!timer.endsAt)return;const tick=()=>setNow(Date.now());tick();const handle=setInterval(tick,500);window.addEventListener('focus',tick);return()=>{clearInterval(handle);window.removeEventListener('focus',tick)}},[timer.endsAt]);
 const left=timer.endsAt?Math.max(0,Math.ceil((timer.endsAt-now)/1000)):timer.remaining;
 useEffect(()=>{
  if(!loaded||!timer.endsAt||left>0||completing.current===timer.id)return;
  completing.current=timer.id;
  const completed=timer;
  void(async()=>{
   if(completed.mode==='work'){
    const saved=await update(d=>d.focus.some(s=>s.id===completed.id)?d:{...d,focus:[...d.focus,{id:completed.id,date:dayKey(new Date(completed.endsAt!)),minutes:completed.minutes}]});
    if(!saved){setTimer(t=>({...t,endsAt:null,remaining:0}));notify('ثبت تمرکز انجام نشد؛ خطای ذخیره‌سازی را بررسی کن و برای تلاش دوباره شروع را بزن.');return;}
    notify('تمرکزت کامل شد. چند لحظه به خودت استراحت بده.');
   }else notify('استراحت تمام شد. آماده یک قدم تازه‌ای؟');
   setTimer(t=>t.id===completed.id?{...t,id:'',endsAt:null,remaining:t.minutes*60}:t);
  })();
 },[left,timer,loaded,update,notify]);
 function choose(minutes:number,mode:'work'|'rest'){if(timer.endsAt&&!confirm('بازه فعلی متوقف و بازنشانی شود؟'))return;setTimer({id:'',minutes,remaining:minutes*60,endsAt:null,mode})}
 const minutes=String(Math.floor(left/60)).padStart(2,'0'),seconds=String(left%60).padStart(2,'0');
 return <section className="g-card g-timer-card" aria-hidden={!active}><div className="g-tabs">{[[25,'تمرکز کوتاه'],[50,'تمرکز عمیق'],[5,'استراحت']].map(([m,label])=><button key={m} className={timer.minutes===m?'selected':''} onClick={()=>choose(Number(m),m===5?'rest':'work')}>{label}</button>)}</div><div className={`g-timer-ring ${timer.endsAt?'running':''}`} style={{'--progress':`${(1-left/(timer.minutes*60))*360}deg`} as React.CSSProperties}><div><Leaf size={28}/><strong dir="ltr">{(minutes+':'+seconds).replace(/\d/g,c=>'۰۱۲۳۴۵۶۷۸۹'[+c])}</strong><span>{timer.endsAt?'فقط همین لحظه، فقط همین کار':timer.mode==='work'?'یک نفس عمیق، و شروع کن':'چشم‌ها و بدنت را استراحت بده'}</span></div></div><div className="g-timer-actions"><button className="g-btn primary" onClick={()=>{completing.current=null;setNow(Date.now());setTimer(t=>t.endsAt?{...t,remaining:left,endsAt:null}:{...t,id:t.id||uid(),endsAt:Date.now()+t.remaining*1000})}}>{timer.endsAt?'توقف موقت':timer.remaining<timer.minutes*60?'ادامه تمرکز':'شروع'}</button><button className="g-btn" onClick={()=>{if(!timer.endsAt||confirm('این بازه بازنشانی شود؟'))setTimer(t=>({...t,id:'',remaining:t.minutes*60,endsAt:null}))}}>از ابتدا</button></div><p>زمان‌سنج هنگام جابه‌جایی بین بخش‌ها ادامه دارد.<br/>اگر اپ بسته باشد، بازه پس از بازگشت محاسبه می‌شود؛ اعلان پس‌زمینه ندارد.</p></section>;
}
