'use client';
import {useEffect,useState} from 'react';
import {RefreshCw,Server,ShieldCheck} from 'lucide-react';
type Operations={version:string;generatedAt:string;runtime:string;database:string;adminConfigured:boolean;backup:{at:string;bytes:number}|null;counts:{members:number;messages:number;reports:number;vaults:number};providers:{name:string;configured:boolean;detail:string}[];limits:string[]};
export default function OperationsAdmin(){
  const [value,setValue]=useState<Operations|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[]);
  async function load(signal?:AbortSignal){setBusy(true);setError('');try{const response=await fetch('/api/operations',{cache:'no-store',signal:signal||AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'وضعیت سرویس دریافت نشد.');setValue(data)}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'خطای اتصال')}finally{if(!signal?.aborted)setBusy(false)}}
  return <section className="admin-card" style={{marginTop:24}}><div className="admin-card-heading"><h2><Server size={18}/> عملیات روشنا +۳۳</h2><button className="admin-button" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/>{busy?'دریافت…':'تازه‌سازی'}</button></div>{error&&<p role="alert">{error}</p>}{value&&<><p className="admin-muted">آخرین دریافت: {new Date(value.generatedAt).toLocaleString('fa-IR')} · Node {value.runtime} · SQLite، یک پردازش</p><div className="admin-stats">{[{label:'حساب فعال',value:value.counts.members},{label:'گزارش باز',value:value.counts.reports},{label:'خزانه رمزگذاری‌شده',value:value.counts.vaults}].map(item=><div className="admin-card" key={item.label}><strong>{item.value.toLocaleString('fa-IR')}</strong><p>{item.label}</p></div>)}</div><div className="admin-info"><ShieldCheck size={20}/><span>{value.backup?`آخرین فایل پشتیبان موجود: ${new Date(value.backup.at).toLocaleString('fa-IR')}؛ وجود فایل به معنی بررسی سلامت یا امکان بازیابی آن نیست.`:'فایل پشتیبان SQLite پیدا نشد؛ دستور npm run backup را روی سرور اجرا کنید.'}</span></div>{value.providers.map(provider=><div key={provider.name} style={{padding:'16px 0',borderBottom:'1px solid var(--line)'}}><strong>{provider.name}</strong><span style={{marginInlineStart:12}}>{provider.configured?'تنظیمات موجود':'نیازمند اتصال'}</span><p className="admin-muted">{provider.detail}</p></div>)}<ul style={{paddingInlineStart:22,marginTop:20,lineHeight:2.2,fontSize:12}}>{value.limits.map(item=><li key={item}>{item}</li>)}</ul></>}</section>;
}
